// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: driver_service.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 司机资质状态
// Driver qualification status
type DriverStatus int32

const (
	DriverStatus_DRIVER_STATUS_UNSPECIFIED DriverStatus = 0 // 未指定
	DriverStatus_DRIVER_STATUS_PENDING     DriverStatus = 1 // 待审核 (Pending review)
	DriverStatus_DRIVER_STATUS_APPROVED    DriverStatus = 2 // 已通过 (Approved)
	DriverStatus_DRIVER_STATUS_REJECTED    DriverStatus = 3 // 已拒绝 (Rejected)
	DriverStatus_DRIVER_STATUS_SUSPENDED   DriverStatus = 4 // 已暂停 (Suspended)
)

// Enum value maps for DriverStatus.
var (
	DriverStatus_name = map[int32]string{
		0: "DRIVER_STATUS_UNSPECIFIED",
		1: "DRIVER_STATUS_PENDING",
		2: "DRIVER_STATUS_APPROVED",
		3: "DRIVER_STATUS_REJECTED",
		4: "DRIVER_STATUS_SUSPENDED",
	}
	DriverStatus_value = map[string]int32{
		"DRIVER_STATUS_UNSPECIFIED": 0,
		"DRIVER_STATUS_PENDING":     1,
		"DRIVER_STATUS_APPROVED":    2,
		"DRIVER_STATUS_REJECTED":    3,
		"DRIVER_STATUS_SUSPENDED":   4,
	}
)

func (x DriverStatus) Enum() *DriverStatus {
	p := new(DriverStatus)
	*p = x
	return p
}

func (x DriverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_driver_service_proto_enumTypes[0].Descriptor()
}

func (DriverStatus) Type() protoreflect.EnumType {
	return &file_driver_service_proto_enumTypes[0]
}

func (x DriverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatus.Descriptor instead.
func (DriverStatus) EnumDescriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{0}
}

// 司机资质信息
// Driver qualification information
type DriverInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // 司机ID (Driver ID)
	Name          string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // 司机姓名 (Driver name)
	Phone         string       `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`                                      // 手机号 (Phone number)
	LicenseNumber string       `protobuf:"bytes,4,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"` // 驾驶证号 (Driver's license number)
	LicenseImage  string       `protobuf:"bytes,5,opt,name=license_image,json=licenseImage,proto3" json:"license_image,omitempty"`    // 驾驶证图片URL (Driver's license image URL)
	VehiclePlate  string       `protobuf:"bytes,6,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`    // 车牌号 (Vehicle plate number)
	VehicleImage  string       `protobuf:"bytes,7,opt,name=vehicle_image,json=vehicleImage,proto3" json:"vehicle_image,omitempty"`    // 车辆图片URL (Vehicle image URL)
	VehicleType   string       `protobuf:"bytes,8,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`       // 车辆类型 (Vehicle type: 出租车/网约车)
	IdCardNumber  string       `protobuf:"bytes,9,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`  // 身份证号 (ID card number)
	IdCardImage   string       `protobuf:"bytes,10,opt,name=id_card_image,json=idCardImage,proto3" json:"id_card_image,omitempty"`    // 身份证图片URL (ID card image URL)
	Status        DriverStatus `protobuf:"varint,11,opt,name=status,proto3,enum=driverProto.DriverStatus" json:"status,omitempty"`    // 资质状态 (Qualification status)
	RejectReason  string       `protobuf:"bytes,12,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`   // 拒绝原因 (Rejection reason)
	CreatedAt     string       `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`            // 创建时间 (Created time)
	UpdatedAt     string       `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`            // 更新时间 (Updated time)
}

func (x *DriverInfo) Reset() {
	*x = DriverInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInfo) ProtoMessage() {}

func (x *DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInfo.ProtoReflect.Descriptor instead.
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{0}
}

func (x *DriverInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverInfo) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DriverInfo) GetLicenseImage() string {
	if x != nil {
		return x.LicenseImage
	}
	return ""
}

func (x *DriverInfo) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *DriverInfo) GetVehicleImage() string {
	if x != nil {
		return x.VehicleImage
	}
	return ""
}

func (x *DriverInfo) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *DriverInfo) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *DriverInfo) GetIdCardImage() string {
	if x != nil {
		return x.IdCardImage
	}
	return ""
}

func (x *DriverInfo) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_DRIVER_STATUS_UNSPECIFIED
}

func (x *DriverInfo) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *DriverInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DriverInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 司机入驻请求
// Driver registration request
type DriverRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // 司机姓名
	Phone         string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`                                      // 手机号
	LicenseNumber string `protobuf:"bytes,3,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"` // 驾驶证号
	LicenseImage  string `protobuf:"bytes,4,opt,name=license_image,json=licenseImage,proto3" json:"license_image,omitempty"`    // 驾驶证图片
	VehiclePlate  string `protobuf:"bytes,5,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`    // 车牌号
	VehicleImage  string `protobuf:"bytes,6,opt,name=vehicle_image,json=vehicleImage,proto3" json:"vehicle_image,omitempty"`    // 车辆图片
	VehicleType   string `protobuf:"bytes,7,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`       // 车辆类型
	IdCardNumber  string `protobuf:"bytes,8,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`  // 身份证号
	IdCardImage   string `protobuf:"bytes,9,opt,name=id_card_image,json=idCardImage,proto3" json:"id_card_image,omitempty"`     // 身份证图片
}

func (x *DriverRegisterReq) Reset() {
	*x = DriverRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegisterReq) ProtoMessage() {}

func (x *DriverRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegisterReq.ProtoReflect.Descriptor instead.
func (*DriverRegisterReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{1}
}

func (x *DriverRegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverRegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverRegisterReq) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DriverRegisterReq) GetLicenseImage() string {
	if x != nil {
		return x.LicenseImage
	}
	return ""
}

func (x *DriverRegisterReq) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *DriverRegisterReq) GetVehicleImage() string {
	if x != nil {
		return x.VehicleImage
	}
	return ""
}

func (x *DriverRegisterReq) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *DriverRegisterReq) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *DriverRegisterReq) GetIdCardImage() string {
	if x != nil {
		return x.IdCardImage
	}
	return ""
}

// 司机入驻响应
// Driver registration response
type DriverRegisterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // 司机ID
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`  // 消息
}

func (x *DriverRegisterRes) Reset() {
	*x = DriverRegisterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverRegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegisterRes) ProtoMessage() {}

func (x *DriverRegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegisterRes.ProtoReflect.Descriptor instead.
func (*DriverRegisterRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{2}
}

func (x *DriverRegisterRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverRegisterRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverRegisterRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 司机列表请求
// Driver list request
type DriverListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	Keyword  string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`                    // 搜索关键字(姓名/手机号/车牌号)
	Status   int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                     // 状态筛选
}

func (x *DriverListReq) Reset() {
	*x = DriverListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverListReq) ProtoMessage() {}

func (x *DriverListReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverListReq.ProtoReflect.Descriptor instead.
func (*DriverListReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{3}
}

func (x *DriverListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DriverListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DriverListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *DriverListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 司机列表响应
// Driver list response
type DriverListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   int32         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`    // 总数
	Drivers []*DriverInfo `protobuf:"bytes,2,rep,name=drivers,proto3" json:"drivers,omitempty"` // 司机列表
}

func (x *DriverListRes) Reset() {
	*x = DriverListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverListRes) ProtoMessage() {}

func (x *DriverListRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverListRes.ProtoReflect.Descriptor instead.
func (*DriverListRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{4}
}

func (x *DriverListRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DriverListRes) GetDrivers() []*DriverInfo {
	if x != nil {
		return x.Drivers
	}
	return nil
}

// 司机详情请求
// Driver detail request
type DriverDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 司机ID
}

func (x *DriverDetailReq) Reset() {
	*x = DriverDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDetailReq) ProtoMessage() {}

func (x *DriverDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDetailReq.ProtoReflect.Descriptor instead.
func (*DriverDetailReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{5}
}

func (x *DriverDetailReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 司机详情响应
// Driver detail response
type DriverDetailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver *DriverInfo `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"` // 司机信息
}

func (x *DriverDetailRes) Reset() {
	*x = DriverDetailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDetailRes) ProtoMessage() {}

func (x *DriverDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDetailRes.ProtoReflect.Descriptor instead.
func (*DriverDetailRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{6}
}

func (x *DriverDetailRes) GetDriver() *DriverInfo {
	if x != nil {
		return x.Driver
	}
	return nil
}

// 司机审核请求
// Driver approval request
type DriverApproveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 司机ID
	Status       int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                                // 审核状态 (2-通过, 3-拒绝)
	RejectReason string `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 拒绝原因(当status为拒绝时必填)
	Remark       string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`                                 // 审核备注 (审核意见/备注)
}

func (x *DriverApproveReq) Reset() {
	*x = DriverApproveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverApproveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverApproveReq) ProtoMessage() {}

func (x *DriverApproveReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverApproveReq.ProtoReflect.Descriptor instead.
func (*DriverApproveReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{7}
}

func (x *DriverApproveReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverApproveReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DriverApproveReq) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *DriverApproveReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 司机审核响应
// Driver approval response
type DriverApproveRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
}

func (x *DriverApproveRes) Reset() {
	*x = DriverApproveRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverApproveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverApproveRes) ProtoMessage() {}

func (x *DriverApproveRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverApproveRes.ProtoReflect.Descriptor instead.
func (*DriverApproveRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{8}
}

func (x *DriverApproveRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverApproveRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 批量司机审核请求
// Batch driver approval request
type DriverBatchApproveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids          []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`                               // 司机ID列表
	Status       int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                                // 审核状态 (2-通过, 3-拒绝)
	RejectReason string   `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 拒绝原因
	Remark       string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`                                 // 审核备注
}

func (x *DriverBatchApproveReq) Reset() {
	*x = DriverBatchApproveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverBatchApproveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverBatchApproveReq) ProtoMessage() {}

func (x *DriverBatchApproveReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverBatchApproveReq.ProtoReflect.Descriptor instead.
func (*DriverBatchApproveReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{9}
}

func (x *DriverBatchApproveReq) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DriverBatchApproveReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DriverBatchApproveReq) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *DriverBatchApproveReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 批量司机审核响应
// Batch driver approval response
type DriverBatchApproveRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessCount int32  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	FailCount    int32  `protobuf:"varint,2,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`          // 失败数量
	Message      string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                // 消息
}

func (x *DriverBatchApproveRes) Reset() {
	*x = DriverBatchApproveRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverBatchApproveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverBatchApproveRes) ProtoMessage() {}

func (x *DriverBatchApproveRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverBatchApproveRes.ProtoReflect.Descriptor instead.
func (*DriverBatchApproveRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{10}
}

func (x *DriverBatchApproveRes) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *DriverBatchApproveRes) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *DriverBatchApproveRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 审核历史记录
// Audit history record
type AuditHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 记录ID
	DriverId  uint32 `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`    // 司机ID
	OldStatus int32  `protobuf:"varint,3,opt,name=old_status,json=oldStatus,proto3" json:"old_status,omitempty"` // 原状态
	NewStatus int32  `protobuf:"varint,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"` // 新状态
	Remark    string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`                         // 审核备注
	Auditor   string `protobuf:"bytes,6,opt,name=auditor,proto3" json:"auditor,omitempty"`                       // 审核人
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // 审核时间
}

func (x *AuditHistory) Reset() {
	*x = AuditHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuditHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditHistory) ProtoMessage() {}

func (x *AuditHistory) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditHistory.ProtoReflect.Descriptor instead.
func (*AuditHistory) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{11}
}

func (x *AuditHistory) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditHistory) GetDriverId() uint32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *AuditHistory) GetOldStatus() int32 {
	if x != nil {
		return x.OldStatus
	}
	return 0
}

func (x *AuditHistory) GetNewStatus() int32 {
	if x != nil {
		return x.NewStatus
	}
	return 0
}

func (x *AuditHistory) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AuditHistory) GetAuditor() string {
	if x != nil {
		return x.Auditor
	}
	return ""
}

func (x *AuditHistory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 审核历史列表请求
// Audit history list request
type AuditHistoryListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriverId uint32 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"` // 司机ID (可选，不填则查全部)
	Page     int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
}

func (x *AuditHistoryListReq) Reset() {
	*x = AuditHistoryListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuditHistoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditHistoryListReq) ProtoMessage() {}

func (x *AuditHistoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditHistoryListReq.ProtoReflect.Descriptor instead.
func (*AuditHistoryListReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{12}
}

func (x *AuditHistoryListReq) GetDriverId() uint32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *AuditHistoryListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AuditHistoryListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 审核历史列表响应
// Audit history list response
type AuditHistoryListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total     int32           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`        // 总数
	Histories []*AuditHistory `protobuf:"bytes,2,rep,name=histories,proto3" json:"histories,omitempty"` // 审核历史列表
}

func (x *AuditHistoryListRes) Reset() {
	*x = AuditHistoryListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuditHistoryListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditHistoryListRes) ProtoMessage() {}

func (x *AuditHistoryListRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditHistoryListRes.ProtoReflect.Descriptor instead.
func (*AuditHistoryListRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{13}
}

func (x *AuditHistoryListRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AuditHistoryListRes) GetHistories() []*AuditHistory {
	if x != nil {
		return x.Histories
	}
	return nil
}

// 司机删除请求
// Driver delete request
type DriverDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 司机ID
}

func (x *DriverDeleteReq) Reset() {
	*x = DriverDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDeleteReq) ProtoMessage() {}

func (x *DriverDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDeleteReq.ProtoReflect.Descriptor instead.
func (*DriverDeleteReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{14}
}

func (x *DriverDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 司机删除响应
// Driver delete response
type DriverDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
}

func (x *DriverDeleteRes) Reset() {
	*x = DriverDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDeleteRes) ProtoMessage() {}

func (x *DriverDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDeleteRes.ProtoReflect.Descriptor instead.
func (*DriverDeleteRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{15}
}

func (x *DriverDeleteRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverDeleteRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_driver_service_proto protoreflect.FileDescriptor

var file_driver_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xdf, 0x03, 0x0a, 0x0a, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69, 0x63, 0x65,
	0x6e, 0x73, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0d, 0x69,
	0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc0, 0x02, 0x0a, 0x11, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c,
	0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d,
	0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24,
	0x0a, 0x0e, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x64, 0x43,
	0x61, 0x72, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x57, 0x0a, 0x11, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x72, 0x0a, 0x0d, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x58, 0x0a, 0x0d, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x31, 0x0a, 0x07,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x22,
	0x21, 0x0a, 0x0f, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x42, 0x0a, 0x0f, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x22, 0x77, 0x0a, 0x10, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22,
	0x46, 0x0a, 0x10, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7e, 0x0a, 0x15, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x03, 0x69,
	0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x75, 0x0a, 0x15, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xca,
	0x01, 0x0a, 0x0c, 0x41, 0x75, 0x64, 0x69, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x6f, 0x6c, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6f, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x65, 0x77, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x75, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x63, 0x0a, 0x13, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x64, 0x0a, 0x13, 0x41, 0x75, 0x64, 0x69, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x37, 0x0a,
	0x09, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0f, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2a, 0x9d, 0x01, 0x0a, 0x0c, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x19, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x19, 0x0a, 0x15, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x44,
	0x52, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x50, 0x50,
	0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x52, 0x49, 0x56, 0x45,
	0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x53, 0x50, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x04,
	0x32, 0xc9, 0x04, 0x0a, 0x0d, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x50, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x4d, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x1c, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1c,
	0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x4d, 0x0a, 0x0d,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1d, 0x2e,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x12, 0x5c, 0x0a, 0x12, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x12, 0x22, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x12, 0x55, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x41, 0x75, 0x64, 0x69, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x2e, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20,
	0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x64,
	0x69, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x4a, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x12, 0x1c, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c,
	0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x62, 0x65, 0x69,
	0x77, 0x61, 0x6e, 0x6a, 0x69, 0x61, 0x2f, 0x72, 0x69, 0x64, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_driver_service_proto_rawDescOnce sync.Once
	file_driver_service_proto_rawDescData = file_driver_service_proto_rawDesc
)

func file_driver_service_proto_rawDescGZIP() []byte {
	file_driver_service_proto_rawDescOnce.Do(func() {
		file_driver_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_driver_service_proto_rawDescData)
	})
	return file_driver_service_proto_rawDescData
}

var file_driver_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_driver_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_driver_service_proto_goTypes = []any{
	(DriverStatus)(0),             // 0: driverProto.DriverStatus
	(*DriverInfo)(nil),            // 1: driverProto.DriverInfo
	(*DriverRegisterReq)(nil),     // 2: driverProto.DriverRegisterReq
	(*DriverRegisterRes)(nil),     // 3: driverProto.DriverRegisterRes
	(*DriverListReq)(nil),         // 4: driverProto.DriverListReq
	(*DriverListRes)(nil),         // 5: driverProto.DriverListRes
	(*DriverDetailReq)(nil),       // 6: driverProto.DriverDetailReq
	(*DriverDetailRes)(nil),       // 7: driverProto.DriverDetailRes
	(*DriverApproveReq)(nil),      // 8: driverProto.DriverApproveReq
	(*DriverApproveRes)(nil),      // 9: driverProto.DriverApproveRes
	(*DriverBatchApproveReq)(nil), // 10: driverProto.DriverBatchApproveReq
	(*DriverBatchApproveRes)(nil), // 11: driverProto.DriverBatchApproveRes
	(*AuditHistory)(nil),          // 12: driverProto.AuditHistory
	(*AuditHistoryListReq)(nil),   // 13: driverProto.AuditHistoryListReq
	(*AuditHistoryListRes)(nil),   // 14: driverProto.AuditHistoryListRes
	(*DriverDeleteReq)(nil),       // 15: driverProto.DriverDeleteReq
	(*DriverDeleteRes)(nil),       // 16: driverProto.DriverDeleteRes
}
var file_driver_service_proto_depIdxs = []int32{
	0,  // 0: driverProto.DriverInfo.status:type_name -> driverProto.DriverStatus
	1,  // 1: driverProto.DriverListRes.drivers:type_name -> driverProto.DriverInfo
	1,  // 2: driverProto.DriverDetailRes.driver:type_name -> driverProto.DriverInfo
	12, // 3: driverProto.AuditHistoryListRes.histories:type_name -> driverProto.AuditHistory
	2,  // 4: driverProto.DriverService.RegisterDriver:input_type -> driverProto.DriverRegisterReq
	4,  // 5: driverProto.DriverService.GetDriverList:input_type -> driverProto.DriverListReq
	6,  // 6: driverProto.DriverService.GetDriverDetail:input_type -> driverProto.DriverDetailReq
	8,  // 7: driverProto.DriverService.ApproveDriver:input_type -> driverProto.DriverApproveReq
	10, // 8: driverProto.DriverService.BatchApproveDriver:input_type -> driverProto.DriverBatchApproveReq
	13, // 9: driverProto.DriverService.GetAuditHistory:input_type -> driverProto.AuditHistoryListReq
	15, // 10: driverProto.DriverService.DeleteDriver:input_type -> driverProto.DriverDeleteReq
	3,  // 11: driverProto.DriverService.RegisterDriver:output_type -> driverProto.DriverRegisterRes
	5,  // 12: driverProto.DriverService.GetDriverList:output_type -> driverProto.DriverListRes
	7,  // 13: driverProto.DriverService.GetDriverDetail:output_type -> driverProto.DriverDetailRes
	9,  // 14: driverProto.DriverService.ApproveDriver:output_type -> driverProto.DriverApproveRes
	11, // 15: driverProto.DriverService.BatchApproveDriver:output_type -> driverProto.DriverBatchApproveRes
	14, // 16: driverProto.DriverService.GetAuditHistory:output_type -> driverProto.AuditHistoryListRes
	16, // 17: driverProto.DriverService.DeleteDriver:output_type -> driverProto.DriverDeleteRes
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_driver_service_proto_init() }
func file_driver_service_proto_init() {
	if File_driver_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_driver_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DriverInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DriverRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DriverRegisterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DriverListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DriverListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DriverDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DriverDetailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DriverApproveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DriverApproveRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DriverBatchApproveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DriverBatchApproveRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*AuditHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AuditHistoryListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AuditHistoryListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*DriverDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_service_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*DriverDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_driver_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_service_proto_goTypes,
		DependencyIndexes: file_driver_service_proto_depIdxs,
		EnumInfos:         file_driver_service_proto_enumTypes,
		MessageInfos:      file_driver_service_proto_msgTypes,
	}.Build()
	File_driver_service_proto = out.File
	file_driver_service_proto_rawDesc = nil
	file_driver_service_proto_goTypes = nil
	file_driver_service_proto_depIdxs = nil
}
