// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: poster_service.proto

package poster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 生成海报请求
type GeneratePosterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QrContent      string `protobuf:"bytes,1,opt,name=qr_content,json=qrContent,proto3" json:"qr_content,omitempty"`                // 二维码内容（链接）
	QrSize         int32  `protobuf:"varint,2,opt,name=qr_size,json=qrSize,proto3" json:"qr_size,omitempty"`                        // 二维码尺寸
	AvatarPath     string `protobuf:"bytes,3,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path,omitempty"`             // 头像图片路径（本地路径或URL）
	AvatarSize     int32  `protobuf:"varint,4,opt,name=avatar_size,json=avatarSize,proto3" json:"avatar_size,omitempty"`            // 头像尺寸
	PosterPath     string `protobuf:"bytes,5,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`             // 海报背景图片路径（本地路径）
	QrX            int32  `protobuf:"varint,6,opt,name=qr_x,json=qrX,proto3" json:"qr_x,omitempty"`                                 // 二维码在海报上的 X 坐标
	QrY            int32  `protobuf:"varint,7,opt,name=qr_y,json=qrY,proto3" json:"qr_y,omitempty"`                                 // 二维码在海报上的 Y 坐标
	OutputDir      string `protobuf:"bytes,8,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`                // 输出目录（可选，默认 ./output）
	OutputFilename string `protobuf:"bytes,9,opt,name=output_filename,json=outputFilename,proto3" json:"output_filename,omitempty"` // 输出文件名（可选，自动生成时间戳文件名）
}

func (x *GeneratePosterRequest) Reset() {
	*x = GeneratePosterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poster_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePosterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePosterRequest) ProtoMessage() {}

func (x *GeneratePosterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poster_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePosterRequest.ProtoReflect.Descriptor instead.
func (*GeneratePosterRequest) Descriptor() ([]byte, []int) {
	return file_poster_service_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePosterRequest) GetQrContent() string {
	if x != nil {
		return x.QrContent
	}
	return ""
}

func (x *GeneratePosterRequest) GetQrSize() int32 {
	if x != nil {
		return x.QrSize
	}
	return 0
}

func (x *GeneratePosterRequest) GetAvatarPath() string {
	if x != nil {
		return x.AvatarPath
	}
	return ""
}

func (x *GeneratePosterRequest) GetAvatarSize() int32 {
	if x != nil {
		return x.AvatarSize
	}
	return 0
}

func (x *GeneratePosterRequest) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *GeneratePosterRequest) GetQrX() int32 {
	if x != nil {
		return x.QrX
	}
	return 0
}

func (x *GeneratePosterRequest) GetQrY() int32 {
	if x != nil {
		return x.QrY
	}
	return 0
}

func (x *GeneratePosterRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *GeneratePosterRequest) GetOutputFilename() string {
	if x != nil {
		return x.OutputFilename
	}
	return ""
}

// 生成海报响应
type GeneratePosterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // 是否成功
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	PosterUrl  string `protobuf:"bytes,3,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`    // 生成的海报图片URL
	PosterPath string `protobuf:"bytes,4,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"` // 生成的海报图片本地路径
}

func (x *GeneratePosterResponse) Reset() {
	*x = GeneratePosterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poster_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePosterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePosterResponse) ProtoMessage() {}

func (x *GeneratePosterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poster_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePosterResponse.ProtoReflect.Descriptor instead.
func (*GeneratePosterResponse) Descriptor() ([]byte, []int) {
	return file_poster_service_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePosterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GeneratePosterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GeneratePosterResponse) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *GeneratePosterResponse) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

var File_poster_service_proto protoreflect.FileDescriptor

var file_poster_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x71, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x71, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x71, 0x72, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x71,
	0x72, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x11, 0x0a, 0x04, 0x71, 0x72, 0x5f, 0x78,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x72, 0x58, 0x12, 0x11, 0x0a, 0x04, 0x71,
	0x72, 0x5f, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x72, 0x59, 0x12, 0x1d,
	0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x69, 0x72, 0x12, 0x27, 0x0a,
	0x0f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x61, 0x74, 0x68, 0x32, 0x6a, 0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70,
	0x6f, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_poster_service_proto_rawDescOnce sync.Once
	file_poster_service_proto_rawDescData = file_poster_service_proto_rawDesc
)

func file_poster_service_proto_rawDescGZIP() []byte {
	file_poster_service_proto_rawDescOnce.Do(func() {
		file_poster_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_poster_service_proto_rawDescData)
	})
	return file_poster_service_proto_rawDescData
}

var file_poster_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_poster_service_proto_goTypes = []any{
	(*GeneratePosterRequest)(nil),  // 0: posterProto.GeneratePosterRequest
	(*GeneratePosterResponse)(nil), // 1: posterProto.GeneratePosterResponse
}
var file_poster_service_proto_depIdxs = []int32{
	0, // 0: posterProto.PosterService.GeneratePoster:input_type -> posterProto.GeneratePosterRequest
	1, // 1: posterProto.PosterService.GeneratePoster:output_type -> posterProto.GeneratePosterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_poster_service_proto_init() }
func file_poster_service_proto_init() {
	if File_poster_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poster_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GeneratePosterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poster_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GeneratePosterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poster_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poster_service_proto_goTypes,
		DependencyIndexes: file_poster_service_proto_depIdxs,
		MessageInfos:      file_poster_service_proto_msgTypes,
	}.Build()
	File_poster_service_proto = out.File
	file_poster_service_proto_rawDesc = nil
	file_poster_service_proto_goTypes = nil
	file_poster_service_proto_depIdxs = nil
}
