// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: homepage.proto

package homepage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	HomePageService_SearchPlace_FullMethodName  = "/homeproto.HomePageService/SearchPlace"
	HomePageService_AroundSearch_FullMethodName = "/homeproto.HomePageService/AroundSearch"
	HomePageService_GeoCode_FullMethodName      = "/homeproto.HomePageService/GeoCode"
	HomePageService_ReGeoCode_FullMethodName    = "/homeproto.HomePageService/ReGeoCode"
)

// HomePageServiceClient is the client API for HomePageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HomePageServiceClient interface {
	// 关键字搜索地点
	SearchPlace(ctx context.Context, in *SearchPlaceReq, opts ...grpc.CallOption) (*SearchPlaceRes, error)
	// 周边搜索
	AroundSearch(ctx context.Context, in *AroundSearchReq, opts ...grpc.CallOption) (*AroundSearchRes, error)
	// 地址转经纬度
	GeoCode(ctx context.Context, in *GeoCodeReq, opts ...grpc.CallOption) (*GeoCodeRes, error)
	// 经纬度转地址
	ReGeoCode(ctx context.Context, in *ReGeoCodeReq, opts ...grpc.CallOption) (*ReGeoCodeRes, error)
}

type homePageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHomePageServiceClient(cc grpc.ClientConnInterface) HomePageServiceClient {
	return &homePageServiceClient{cc}
}

func (c *homePageServiceClient) SearchPlace(ctx context.Context, in *SearchPlaceReq, opts ...grpc.CallOption) (*SearchPlaceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPlaceRes)
	err := c.cc.Invoke(ctx, HomePageService_SearchPlace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homePageServiceClient) AroundSearch(ctx context.Context, in *AroundSearchReq, opts ...grpc.CallOption) (*AroundSearchRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AroundSearchRes)
	err := c.cc.Invoke(ctx, HomePageService_AroundSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homePageServiceClient) GeoCode(ctx context.Context, in *GeoCodeReq, opts ...grpc.CallOption) (*GeoCodeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoCodeRes)
	err := c.cc.Invoke(ctx, HomePageService_GeoCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homePageServiceClient) ReGeoCode(ctx context.Context, in *ReGeoCodeReq, opts ...grpc.CallOption) (*ReGeoCodeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReGeoCodeRes)
	err := c.cc.Invoke(ctx, HomePageService_ReGeoCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomePageServiceServer is the server API for HomePageService service.
// All implementations must embed UnimplementedHomePageServiceServer
// for forward compatibility
type HomePageServiceServer interface {
	// 关键字搜索地点
	SearchPlace(context.Context, *SearchPlaceReq) (*SearchPlaceRes, error)
	// 周边搜索
	AroundSearch(context.Context, *AroundSearchReq) (*AroundSearchRes, error)
	// 地址转经纬度
	GeoCode(context.Context, *GeoCodeReq) (*GeoCodeRes, error)
	// 经纬度转地址
	ReGeoCode(context.Context, *ReGeoCodeReq) (*ReGeoCodeRes, error)
	mustEmbedUnimplementedHomePageServiceServer()
}

// UnimplementedHomePageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHomePageServiceServer struct {
}

func (UnimplementedHomePageServiceServer) SearchPlace(context.Context, *SearchPlaceReq) (*SearchPlaceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPlace not implemented")
}
func (UnimplementedHomePageServiceServer) AroundSearch(context.Context, *AroundSearchReq) (*AroundSearchRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AroundSearch not implemented")
}
func (UnimplementedHomePageServiceServer) GeoCode(context.Context, *GeoCodeReq) (*GeoCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeoCode not implemented")
}
func (UnimplementedHomePageServiceServer) ReGeoCode(context.Context, *ReGeoCodeReq) (*ReGeoCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReGeoCode not implemented")
}
func (UnimplementedHomePageServiceServer) mustEmbedUnimplementedHomePageServiceServer() {}

// UnsafeHomePageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HomePageServiceServer will
// result in compilation errors.
type UnsafeHomePageServiceServer interface {
	mustEmbedUnimplementedHomePageServiceServer()
}

func RegisterHomePageServiceServer(s grpc.ServiceRegistrar, srv HomePageServiceServer) {
	s.RegisterService(&HomePageService_ServiceDesc, srv)
}

func _HomePageService_SearchPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomePageServiceServer).SearchPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomePageService_SearchPlace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomePageServiceServer).SearchPlace(ctx, req.(*SearchPlaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomePageService_AroundSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AroundSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomePageServiceServer).AroundSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomePageService_AroundSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomePageServiceServer).AroundSearch(ctx, req.(*AroundSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomePageService_GeoCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomePageServiceServer).GeoCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomePageService_GeoCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomePageServiceServer).GeoCode(ctx, req.(*GeoCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomePageService_ReGeoCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReGeoCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomePageServiceServer).ReGeoCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomePageService_ReGeoCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomePageServiceServer).ReGeoCode(ctx, req.(*ReGeoCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HomePageService_ServiceDesc is the grpc.ServiceDesc for HomePageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HomePageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "homeproto.HomePageService",
	HandlerType: (*HomePageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchPlace",
			Handler:    _HomePageService_SearchPlace_Handler,
		},
		{
			MethodName: "AroundSearch",
			Handler:    _HomePageService_AroundSearch_Handler,
		},
		{
			MethodName: "GeoCode",
			Handler:    _HomePageService_GeoCode_Handler,
		},
		{
			MethodName: "ReGeoCode",
			Handler:    _HomePageService_ReGeoCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "homepage.proto",
}
