// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: homepage.proto

package homepage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 关键字搜索 ==========
type SearchPlaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // 搜索关键字
	City    string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`       // 城市
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`       // 类型
	Page    int32  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`      // 页码
	Offset  int32  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`  // 每页数量
}

func (x *SearchPlaceReq) Reset() {
	*x = SearchPlaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPlaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlaceReq) ProtoMessage() {}

func (x *SearchPlaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlaceReq.ProtoReflect.Descriptor instead.
func (*SearchPlaceReq) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPlaceReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchPlaceReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SearchPlaceReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchPlaceReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchPlaceReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchPlaceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int32        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`  // 总数
	Places []*PlaceInfo `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"` // 地点列表
}

func (x *SearchPlaceRes) Reset() {
	*x = SearchPlaceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPlaceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlaceRes) ProtoMessage() {}

func (x *SearchPlaceRes) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlaceRes.ProtoReflect.Descriptor instead.
func (*SearchPlaceRes) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPlaceRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchPlaceRes) GetPlaces() []*PlaceInfo {
	if x != nil {
		return x.Places
	}
	return nil
}

type PlaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // 名称
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`   // 地址
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"` // 经纬度
	Type     string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`         // 类型
	Distance string `protobuf:"bytes,5,opt,name=distance,proto3" json:"distance,omitempty"` // 距离
}

func (x *PlaceInfo) Reset() {
	*x = PlaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceInfo) ProtoMessage() {}

func (x *PlaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceInfo.ProtoReflect.Descriptor instead.
func (*PlaceInfo) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PlaceInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PlaceInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlaceInfo) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

// ========== 周边搜索 ==========
type AroundSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword  string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`   // 搜索关键字
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"` // 当前位置经纬度，格式：经度,纬度
	City     string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`         // 城市
	Radius   int32  `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`    // 搜索半径（米）
	Page     int32  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`        // 页码
	Offset   int32  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`    // 每页数量
}

func (x *AroundSearchReq) Reset() {
	*x = AroundSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AroundSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AroundSearchReq) ProtoMessage() {}

func (x *AroundSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AroundSearchReq.ProtoReflect.Descriptor instead.
func (*AroundSearchReq) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{3}
}

func (x *AroundSearchReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *AroundSearchReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AroundSearchReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AroundSearchReq) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *AroundSearchReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AroundSearchReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AroundSearchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int32        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Places []*PlaceInfo `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *AroundSearchRes) Reset() {
	*x = AroundSearchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AroundSearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AroundSearchRes) ProtoMessage() {}

func (x *AroundSearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AroundSearchRes.ProtoReflect.Descriptor instead.
func (*AroundSearchRes) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{4}
}

func (x *AroundSearchRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AroundSearchRes) GetPlaces() []*PlaceInfo {
	if x != nil {
		return x.Places
	}
	return nil
}

// ========== 地理编码（地址→经纬度）==========
type GeoCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 地址
	City    string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`       // 城市
}

func (x *GeoCodeReq) Reset() {
	*x = GeoCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoCodeReq) ProtoMessage() {}

func (x *GeoCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoCodeReq.ProtoReflect.Descriptor instead.
func (*GeoCodeReq) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{5}
}

func (x *GeoCodeReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GeoCodeReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GeoCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"` // 经纬度，格式：经度,纬度
	Province string `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"` // 省份
	City     string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`         // 城市
	District string `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"` // 区县
}

func (x *GeoCodeRes) Reset() {
	*x = GeoCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoCodeRes) ProtoMessage() {}

func (x *GeoCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoCodeRes.ProtoReflect.Descriptor instead.
func (*GeoCodeRes) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{6}
}

func (x *GeoCodeRes) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GeoCodeRes) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GeoCodeRes) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoCodeRes) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

// ========== 逆地理编码（经纬度→地址）==========
type ReGeoCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"` // 经纬度，格式：经度,纬度
}

func (x *ReGeoCodeReq) Reset() {
	*x = ReGeoCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReGeoCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReGeoCodeReq) ProtoMessage() {}

func (x *ReGeoCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReGeoCodeReq.ProtoReflect.Descriptor instead.
func (*ReGeoCodeReq) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{7}
}

func (x *ReGeoCodeReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ReGeoCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`   // 详细地址
	Province string `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"` // 省份
	City     string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`         // 城市
	District string `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"` // 区县
	Street   string `protobuf:"bytes,5,opt,name=street,proto3" json:"street,omitempty"`     // 街道
}

func (x *ReGeoCodeRes) Reset() {
	*x = ReGeoCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReGeoCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReGeoCodeRes) ProtoMessage() {}

func (x *ReGeoCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReGeoCodeRes.ProtoReflect.Descriptor instead.
func (*ReGeoCodeRes) Descriptor() ([]byte, []int) {
	return file_homepage_proto_rawDescGZIP(), []int{8}
}

func (x *ReGeoCodeRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReGeoCodeRes) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ReGeoCodeRes) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ReGeoCodeRes) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *ReGeoCodeRes) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

var File_homepage_proto protoreflect.FileDescriptor

var file_homepage_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x0e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x54, 0x0a, 0x0e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x73, 0x22, 0x85, 0x01, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x0f, 0x41, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x55, 0x0a, 0x0f, 0x41,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x22, 0x3a, 0x0a, 0x0a, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x74,
	0x0a, 0x0a, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x22, 0x2a, 0x0a, 0x0c, 0x52, 0x65, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x32,
	0x9e, 0x02, 0x0a, 0x0f, 0x48, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x12, 0x19, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x41, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x2e, 0x68, 0x6f, 0x6d,
	0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x07, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x15, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x09, 0x52, 0x65, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x2e, 0x68,
	0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x47, 0x65, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x69, 0x62, 0x65, 0x69, 0x77, 0x61, 0x6e, 0x6a, 0x69, 0x61, 0x2f, 0x72, 0x69, 0x64, 0x65, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_homepage_proto_rawDescOnce sync.Once
	file_homepage_proto_rawDescData = file_homepage_proto_rawDesc
)

func file_homepage_proto_rawDescGZIP() []byte {
	file_homepage_proto_rawDescOnce.Do(func() {
		file_homepage_proto_rawDescData = protoimpl.X.CompressGZIP(file_homepage_proto_rawDescData)
	})
	return file_homepage_proto_rawDescData
}

var file_homepage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_homepage_proto_goTypes = []any{
	(*SearchPlaceReq)(nil),  // 0: homeproto.SearchPlaceReq
	(*SearchPlaceRes)(nil),  // 1: homeproto.SearchPlaceRes
	(*PlaceInfo)(nil),       // 2: homeproto.PlaceInfo
	(*AroundSearchReq)(nil), // 3: homeproto.AroundSearchReq
	(*AroundSearchRes)(nil), // 4: homeproto.AroundSearchRes
	(*GeoCodeReq)(nil),      // 5: homeproto.GeoCodeReq
	(*GeoCodeRes)(nil),      // 6: homeproto.GeoCodeRes
	(*ReGeoCodeReq)(nil),    // 7: homeproto.ReGeoCodeReq
	(*ReGeoCodeRes)(nil),    // 8: homeproto.ReGeoCodeRes
}
var file_homepage_proto_depIdxs = []int32{
	2, // 0: homeproto.SearchPlaceRes.places:type_name -> homeproto.PlaceInfo
	2, // 1: homeproto.AroundSearchRes.places:type_name -> homeproto.PlaceInfo
	0, // 2: homeproto.HomePageService.SearchPlace:input_type -> homeproto.SearchPlaceReq
	3, // 3: homeproto.HomePageService.AroundSearch:input_type -> homeproto.AroundSearchReq
	5, // 4: homeproto.HomePageService.GeoCode:input_type -> homeproto.GeoCodeReq
	7, // 5: homeproto.HomePageService.ReGeoCode:input_type -> homeproto.ReGeoCodeReq
	1, // 6: homeproto.HomePageService.SearchPlace:output_type -> homeproto.SearchPlaceRes
	4, // 7: homeproto.HomePageService.AroundSearch:output_type -> homeproto.AroundSearchRes
	6, // 8: homeproto.HomePageService.GeoCode:output_type -> homeproto.GeoCodeRes
	8, // 9: homeproto.HomePageService.ReGeoCode:output_type -> homeproto.ReGeoCodeRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_homepage_proto_init() }
func file_homepage_proto_init() {
	if File_homepage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_homepage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearchPlaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SearchPlaceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PlaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AroundSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AroundSearchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GeoCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GeoCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ReGeoCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ReGeoCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_homepage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_homepage_proto_goTypes,
		DependencyIndexes: file_homepage_proto_depIdxs,
		MessageInfos:      file_homepage_proto_msgTypes,
	}.Build()
	File_homepage_proto = out.File
	file_homepage_proto_rawDesc = nil
	file_homepage_proto_goTypes = nil
	file_homepage_proto_depIdxs = nil
}
