// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: poster_service.proto

package poster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 生成海报请求
type GeneratePosterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QrContent      string                 `protobuf:"bytes,1,opt,name=qr_content,json=qrContent,proto3" json:"qr_content,omitempty"`                // 二维码内容（链接）
	QrSize         int32                  `protobuf:"varint,2,opt,name=qr_size,json=qrSize,proto3" json:"qr_size,omitempty"`                        // 二维码尺寸
	AvatarPath     string                 `protobuf:"bytes,3,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path,omitempty"`             // 头像图片路径（本地路径或URL）
	AvatarSize     int32                  `protobuf:"varint,4,opt,name=avatar_size,json=avatarSize,proto3" json:"avatar_size,omitempty"`            // 头像尺寸
	PosterPath     string                 `protobuf:"bytes,5,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`             // 海报背景图片路径（本地路径）
	QrX            int32                  `protobuf:"varint,6,opt,name=qr_x,json=qrX,proto3" json:"qr_x,omitempty"`                                 // 二维码在海报上的 X 坐标
	QrY            int32                  `protobuf:"varint,7,opt,name=qr_y,json=qrY,proto3" json:"qr_y,omitempty"`                                 // 二维码在海报上的 Y 坐标
	OutputDir      string                 `protobuf:"bytes,8,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`                // 输出目录（可选，默认 ./output）
	OutputFilename string                 `protobuf:"bytes,9,opt,name=output_filename,json=outputFilename,proto3" json:"output_filename,omitempty"` // 输出文件名（可选，自动生成时间戳文件名）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GeneratePosterRequest) Reset() {
	*x = GeneratePosterRequest{}
	mi := &file_poster_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePosterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePosterRequest) ProtoMessage() {}

func (x *GeneratePosterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poster_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePosterRequest.ProtoReflect.Descriptor instead.
func (*GeneratePosterRequest) Descriptor() ([]byte, []int) {
	return file_poster_service_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePosterRequest) GetQrContent() string {
	if x != nil {
		return x.QrContent
	}
	return ""
}

func (x *GeneratePosterRequest) GetQrSize() int32 {
	if x != nil {
		return x.QrSize
	}
	return 0
}

func (x *GeneratePosterRequest) GetAvatarPath() string {
	if x != nil {
		return x.AvatarPath
	}
	return ""
}

func (x *GeneratePosterRequest) GetAvatarSize() int32 {
	if x != nil {
		return x.AvatarSize
	}
	return 0
}

func (x *GeneratePosterRequest) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *GeneratePosterRequest) GetQrX() int32 {
	if x != nil {
		return x.QrX
	}
	return 0
}

func (x *GeneratePosterRequest) GetQrY() int32 {
	if x != nil {
		return x.QrY
	}
	return 0
}

func (x *GeneratePosterRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *GeneratePosterRequest) GetOutputFilename() string {
	if x != nil {
		return x.OutputFilename
	}
	return ""
}

// 生成海报响应
type GeneratePosterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	PosterUrl     string                 `protobuf:"bytes,3,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`    // 生成的海报图片URL
	PosterPath    string                 `protobuf:"bytes,4,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"` // 生成的海报图片本地路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePosterResponse) Reset() {
	*x = GeneratePosterResponse{}
	mi := &file_poster_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePosterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePosterResponse) ProtoMessage() {}

func (x *GeneratePosterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poster_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePosterResponse.ProtoReflect.Descriptor instead.
func (*GeneratePosterResponse) Descriptor() ([]byte, []int) {
	return file_poster_service_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePosterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GeneratePosterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GeneratePosterResponse) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *GeneratePosterResponse) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

var File_poster_service_proto protoreflect.FileDescriptor

const file_poster_service_proto_rawDesc = "" +
	"\n" +
	"\x14poster_service.proto\x12\vposterProto\"\xa0\x02\n" +
	"\x15GeneratePosterRequest\x12\x1d\n" +
	"\n" +
	"qr_content\x18\x01 \x01(\tR\tqrContent\x12\x17\n" +
	"\aqr_size\x18\x02 \x01(\x05R\x06qrSize\x12\x1f\n" +
	"\vavatar_path\x18\x03 \x01(\tR\n" +
	"avatarPath\x12\x1f\n" +
	"\vavatar_size\x18\x04 \x01(\x05R\n" +
	"avatarSize\x12\x1f\n" +
	"\vposter_path\x18\x05 \x01(\tR\n" +
	"posterPath\x12\x11\n" +
	"\x04qr_x\x18\x06 \x01(\x05R\x03qrX\x12\x11\n" +
	"\x04qr_y\x18\a \x01(\x05R\x03qrY\x12\x1d\n" +
	"\n" +
	"output_dir\x18\b \x01(\tR\toutputDir\x12'\n" +
	"\x0foutput_filename\x18\t \x01(\tR\x0eoutputFilename\"\x8c\x01\n" +
	"\x16GeneratePosterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x03 \x01(\tR\tposterUrl\x12\x1f\n" +
	"\vposter_path\x18\x04 \x01(\tR\n" +
	"posterPath2j\n" +
	"\rPosterService\x12Y\n" +
	"\x0eGeneratePoster\x12\".posterProto.GeneratePosterRequest\x1a#.posterProto.GeneratePosterResponseB\n" +
	"Z\b./posterb\x06proto3"

var (
	file_poster_service_proto_rawDescOnce sync.Once
	file_poster_service_proto_rawDescData []byte
)

func file_poster_service_proto_rawDescGZIP() []byte {
	file_poster_service_proto_rawDescOnce.Do(func() {
		file_poster_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poster_service_proto_rawDesc), len(file_poster_service_proto_rawDesc)))
	})
	return file_poster_service_proto_rawDescData
}

var file_poster_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_poster_service_proto_goTypes = []any{
	(*GeneratePosterRequest)(nil),  // 0: posterProto.GeneratePosterRequest
	(*GeneratePosterResponse)(nil), // 1: posterProto.GeneratePosterResponse
}
var file_poster_service_proto_depIdxs = []int32{
	0, // 0: posterProto.PosterService.GeneratePoster:input_type -> posterProto.GeneratePosterRequest
	1, // 1: posterProto.PosterService.GeneratePoster:output_type -> posterProto.GeneratePosterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_poster_service_proto_init() }
func file_poster_service_proto_init() {
	if File_poster_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poster_service_proto_rawDesc), len(file_poster_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poster_service_proto_goTypes,
		DependencyIndexes: file_poster_service_proto_depIdxs,
		MessageInfos:      file_poster_service_proto_msgTypes,
	}.Build()
	File_poster_service_proto = out.File
	file_poster_service_proto_goTypes = nil
	file_poster_service_proto_depIdxs = nil
}
