// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: poster_service.proto

package poster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PosterService_GeneratePoster_FullMethodName = "/posterProto.PosterService/GeneratePoster"
)

// PosterServiceClient is the client API for PosterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 海报服务
type PosterServiceClient interface {
	// 生成带二维码的海报
	GeneratePoster(ctx context.Context, in *GeneratePosterRequest, opts ...grpc.CallOption) (*GeneratePosterResponse, error)
}

type posterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPosterServiceClient(cc grpc.ClientConnInterface) PosterServiceClient {
	return &posterServiceClient{cc}
}

func (c *posterServiceClient) GeneratePoster(ctx context.Context, in *GeneratePosterRequest, opts ...grpc.CallOption) (*GeneratePosterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePosterResponse)
	err := c.cc.Invoke(ctx, PosterService_GeneratePoster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PosterServiceServer is the server API for PosterService service.
// All implementations must embed UnimplementedPosterServiceServer
// for forward compatibility.
//
// 海报服务
type PosterServiceServer interface {
	// 生成带二维码的海报
	GeneratePoster(context.Context, *GeneratePosterRequest) (*GeneratePosterResponse, error)
	mustEmbedUnimplementedPosterServiceServer()
}

// UnimplementedPosterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPosterServiceServer struct{}

func (UnimplementedPosterServiceServer) GeneratePoster(context.Context, *GeneratePosterRequest) (*GeneratePosterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePoster not implemented")
}
func (UnimplementedPosterServiceServer) mustEmbedUnimplementedPosterServiceServer() {}
func (UnimplementedPosterServiceServer) testEmbeddedByValue()                       {}

// UnsafePosterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PosterServiceServer will
// result in compilation errors.
type UnsafePosterServiceServer interface {
	mustEmbedUnimplementedPosterServiceServer()
}

func RegisterPosterServiceServer(s grpc.ServiceRegistrar, srv PosterServiceServer) {
	// If the following call panics, it indicates UnimplementedPosterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PosterService_ServiceDesc, srv)
}

func _PosterService_GeneratePoster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePosterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosterServiceServer).GeneratePoster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PosterService_GeneratePoster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosterServiceServer).GeneratePoster(ctx, req.(*GeneratePosterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PosterService_ServiceDesc is the grpc.ServiceDesc for PosterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PosterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "posterProto.PosterService",
	HandlerType: (*PosterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePoster",
			Handler:    _PosterService_GeneratePoster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poster_service.proto",
}
