// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: review_info.proto

package review

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ReviewInfo_CreateReview_FullMethodName     = "/reviewproto.ReviewInfo/CreateReview"
	ReviewInfo_GetUserReviews_FullMethodName   = "/reviewproto.ReviewInfo/GetUserReviews"
	ReviewInfo_GetDriverReviews_FullMethodName = "/reviewproto.ReviewInfo/GetDriverReviews"
	ReviewInfo_GetReviewDetail_FullMethodName  = "/reviewproto.ReviewInfo/GetReviewDetail"
)

// ReviewInfoClient is the client API for ReviewInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewInfoClient interface {
	// 创建评价
	CreateReview(ctx context.Context, in *ReviewCreateReq, opts ...grpc.CallOption) (*ReviewCreateRes, error)
	// 获取评价列表（用户视角）
	GetUserReviews(ctx context.Context, in *UserReviewsReq, opts ...grpc.CallOption) (*UserReviewsRes, error)
	// 获取评价列表（司机视角）
	GetDriverReviews(ctx context.Context, in *DriverReviewsReq, opts ...grpc.CallOption) (*DriverReviewsRes, error)
	// 获取单个评价详情
	GetReviewDetail(ctx context.Context, in *ReviewDetailReq, opts ...grpc.CallOption) (*ReviewDetailRes, error)
}

type reviewInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewInfoClient(cc grpc.ClientConnInterface) ReviewInfoClient {
	return &reviewInfoClient{cc}
}

func (c *reviewInfoClient) CreateReview(ctx context.Context, in *ReviewCreateReq, opts ...grpc.CallOption) (*ReviewCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewCreateRes)
	err := c.cc.Invoke(ctx, ReviewInfo_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewInfoClient) GetUserReviews(ctx context.Context, in *UserReviewsReq, opts ...grpc.CallOption) (*UserReviewsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReviewsRes)
	err := c.cc.Invoke(ctx, ReviewInfo_GetUserReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewInfoClient) GetDriverReviews(ctx context.Context, in *DriverReviewsReq, opts ...grpc.CallOption) (*DriverReviewsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverReviewsRes)
	err := c.cc.Invoke(ctx, ReviewInfo_GetDriverReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewInfoClient) GetReviewDetail(ctx context.Context, in *ReviewDetailReq, opts ...grpc.CallOption) (*ReviewDetailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewDetailRes)
	err := c.cc.Invoke(ctx, ReviewInfo_GetReviewDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewInfoServer is the server API for ReviewInfo service.
// All implementations must embed UnimplementedReviewInfoServer
// for forward compatibility
type ReviewInfoServer interface {
	// 创建评价
	CreateReview(context.Context, *ReviewCreateReq) (*ReviewCreateRes, error)
	// 获取评价列表（用户视角）
	GetUserReviews(context.Context, *UserReviewsReq) (*UserReviewsRes, error)
	// 获取评价列表（司机视角）
	GetDriverReviews(context.Context, *DriverReviewsReq) (*DriverReviewsRes, error)
	// 获取单个评价详情
	GetReviewDetail(context.Context, *ReviewDetailReq) (*ReviewDetailRes, error)
	mustEmbedUnimplementedReviewInfoServer()
}

// UnimplementedReviewInfoServer must be embedded to have forward compatible implementations.
type UnimplementedReviewInfoServer struct {
}

func (UnimplementedReviewInfoServer) CreateReview(context.Context, *ReviewCreateReq) (*ReviewCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedReviewInfoServer) GetUserReviews(context.Context, *UserReviewsReq) (*UserReviewsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserReviews not implemented")
}
func (UnimplementedReviewInfoServer) GetDriverReviews(context.Context, *DriverReviewsReq) (*DriverReviewsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDriverReviews not implemented")
}
func (UnimplementedReviewInfoServer) GetReviewDetail(context.Context, *ReviewDetailReq) (*ReviewDetailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviewDetail not implemented")
}
func (UnimplementedReviewInfoServer) mustEmbedUnimplementedReviewInfoServer() {}

// UnsafeReviewInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewInfoServer will
// result in compilation errors.
type UnsafeReviewInfoServer interface {
	mustEmbedUnimplementedReviewInfoServer()
}

func RegisterReviewInfoServer(s grpc.ServiceRegistrar, srv ReviewInfoServer) {
	s.RegisterService(&ReviewInfo_ServiceDesc, srv)
}

func _ReviewInfo_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewInfoServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewInfo_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewInfoServer).CreateReview(ctx, req.(*ReviewCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewInfo_GetUserReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReviewsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewInfoServer).GetUserReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewInfo_GetUserReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewInfoServer).GetUserReviews(ctx, req.(*UserReviewsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewInfo_GetDriverReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverReviewsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewInfoServer).GetDriverReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewInfo_GetDriverReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewInfoServer).GetDriverReviews(ctx, req.(*DriverReviewsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewInfo_GetReviewDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewInfoServer).GetReviewDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewInfo_GetReviewDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewInfoServer).GetReviewDetail(ctx, req.(*ReviewDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewInfo_ServiceDesc is the grpc.ServiceDesc for ReviewInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reviewproto.ReviewInfo",
	HandlerType: (*ReviewInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReview",
			Handler:    _ReviewInfo_CreateReview_Handler,
		},
		{
			MethodName: "GetUserReviews",
			Handler:    _ReviewInfo_GetUserReviews_Handler,
		},
		{
			MethodName: "GetDriverReviews",
			Handler:    _ReviewInfo_GetDriverReviews_Handler,
		},
		{
			MethodName: "GetReviewDetail",
			Handler:    _ReviewInfo_GetReviewDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review_info.proto",
}
