// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: driver_service.proto

package driver_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverInfo_GetDriverList_FullMethodName         = "/driverProto.DriverInfo/GetDriverList"
	DriverInfo_GetDriverById_FullMethodName         = "/driverProto.DriverInfo/GetDriverById"
	DriverInfo_GetAvailableDrivers_FullMethodName   = "/driverProto.DriverInfo/GetAvailableDrivers"
	DriverInfo_UpdateDrixverLocation_FullMethodName = "/driverProto.DriverInfo/UpdateDrixverLocation"
)

// DriverInfoClient is the client API for DriverInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverInfoClient interface {
	GetDriverList(ctx context.Context, in *GetDriverListReq, opts ...grpc.CallOption) (*GetDriverListRes, error)
	GetDriverById(ctx context.Context, in *GetDriverByIdReq, opts ...grpc.CallOption) (*GetDriverByIdRes, error)
	GetAvailableDrivers(ctx context.Context, in *GetAvailableDriversReq, opts ...grpc.CallOption) (*GetAvailableDriversRes, error)
	UpdateDrixverLocation(ctx context.Context, in *UpdateDriverLocationReq, opts ...grpc.CallOption) (*UpdateDriverLocationRes, error)
}

type driverInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverInfoClient(cc grpc.ClientConnInterface) DriverInfoClient {
	return &driverInfoClient{cc}
}

func (c *driverInfoClient) GetDriverList(ctx context.Context, in *GetDriverListReq, opts ...grpc.CallOption) (*GetDriverListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverListRes)
	err := c.cc.Invoke(ctx, DriverInfo_GetDriverList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverInfoClient) GetDriverById(ctx context.Context, in *GetDriverByIdReq, opts ...grpc.CallOption) (*GetDriverByIdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverByIdRes)
	err := c.cc.Invoke(ctx, DriverInfo_GetDriverById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverInfoClient) GetAvailableDrivers(ctx context.Context, in *GetAvailableDriversReq, opts ...grpc.CallOption) (*GetAvailableDriversRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableDriversRes)
	err := c.cc.Invoke(ctx, DriverInfo_GetAvailableDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverInfoClient) UpdateDrixverLocation(ctx context.Context, in *UpdateDriverLocationReq, opts ...grpc.CallOption) (*UpdateDriverLocationRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDriverLocationRes)
	err := c.cc.Invoke(ctx, DriverInfo_UpdateDrixverLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverInfoServer is the server API for DriverInfo service.
// All implementations must embed UnimplementedDriverInfoServer
// for forward compatibility.
type DriverInfoServer interface {
	GetDriverList(context.Context, *GetDriverListReq) (*GetDriverListRes, error)
	GetDriverById(context.Context, *GetDriverByIdReq) (*GetDriverByIdRes, error)
	GetAvailableDrivers(context.Context, *GetAvailableDriversReq) (*GetAvailableDriversRes, error)
	UpdateDrixverLocation(context.Context, *UpdateDriverLocationReq) (*UpdateDriverLocationRes, error)
	mustEmbedUnimplementedDriverInfoServer()
}

// UnimplementedDriverInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverInfoServer struct{}

func (UnimplementedDriverInfoServer) GetDriverList(context.Context, *GetDriverListReq) (*GetDriverListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverList not implemented")
}
func (UnimplementedDriverInfoServer) GetDriverById(context.Context, *GetDriverByIdReq) (*GetDriverByIdRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverById not implemented")
}
func (UnimplementedDriverInfoServer) GetAvailableDrivers(context.Context, *GetAvailableDriversReq) (*GetAvailableDriversRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableDrivers not implemented")
}
func (UnimplementedDriverInfoServer) UpdateDrixverLocation(context.Context, *UpdateDriverLocationReq) (*UpdateDriverLocationRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDrixverLocation not implemented")
}
func (UnimplementedDriverInfoServer) mustEmbedUnimplementedDriverInfoServer() {}
func (UnimplementedDriverInfoServer) testEmbeddedByValue()                    {}

// UnsafeDriverInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverInfoServer will
// result in compilation errors.
type UnsafeDriverInfoServer interface {
	mustEmbedUnimplementedDriverInfoServer()
}

func RegisterDriverInfoServer(s grpc.ServiceRegistrar, srv DriverInfoServer) {
	// If the following call panics, it indicates UnimplementedDriverInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverInfo_ServiceDesc, srv)
}

func _DriverInfo_GetDriverList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverInfoServer).GetDriverList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverInfo_GetDriverList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverInfoServer).GetDriverList(ctx, req.(*GetDriverListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverInfo_GetDriverById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverInfoServer).GetDriverById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverInfo_GetDriverById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverInfoServer).GetDriverById(ctx, req.(*GetDriverByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverInfo_GetAvailableDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableDriversReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverInfoServer).GetAvailableDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverInfo_GetAvailableDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverInfoServer).GetAvailableDrivers(ctx, req.(*GetAvailableDriversReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverInfo_UpdateDrixverLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverLocationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverInfoServer).UpdateDrixverLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverInfo_UpdateDrixverLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverInfoServer).UpdateDrixverLocation(ctx, req.(*UpdateDriverLocationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverInfo_ServiceDesc is the grpc.ServiceDesc for DriverInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driverProto.DriverInfo",
	HandlerType: (*DriverInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDriverList",
			Handler:    _DriverInfo_GetDriverList_Handler,
		},
		{
			MethodName: "GetDriverById",
			Handler:    _DriverInfo_GetDriverById_Handler,
		},
		{
			MethodName: "GetAvailableDrivers",
			Handler:    _DriverInfo_GetAvailableDrivers_Handler,
		},
		{
			MethodName: "UpdateDrixverLocation",
			Handler:    _DriverInfo_UpdateDrixverLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver_service.proto",
}
