// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: driver_service.proto

package driver_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 更新位置服务,司机和乘客/目的地之间的距离
type UpdateDriverLocationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      uint32                 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"` // 司机ID
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`                          // 当前位置纬度
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`                          // 当前位置经度
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                     // 司机状态（可选，0-空闲，1-服务中，2-下线）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationReq) Reset() {
	*x = UpdateDriverLocationReq{}
	mi := &file_driver_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationReq) ProtoMessage() {}

func (x *UpdateDriverLocationReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationReq.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDriverLocationReq) GetDriverId() uint32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UpdateDriverLocationReq) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateDriverLocationReq) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *UpdateDriverLocationReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateDriverLocationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                      // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                       // 结果消息
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间(时间戳)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationRes) Reset() {
	*x = UpdateDriverLocationRes{}
	mi := &file_driver_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationRes) ProtoMessage() {}

func (x *UpdateDriverLocationRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationRes.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDriverLocationRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDriverLocationRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateDriverLocationRes) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetDriverListReq 获取司机列表请求
type GetDriverListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                     // 司机状态筛选（0-全部，1-空闲，2-服务中，3-下线）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverListReq) Reset() {
	*x = GetDriverListReq{}
	mi := &file_driver_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverListReq) ProtoMessage() {}

func (x *GetDriverListReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverListReq.ProtoReflect.Descriptor instead.
func (*GetDriverListReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetDriverListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDriverListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetDriverListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// GetDriverListRes 获取司机列表响应
type GetDriverListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*DriverDetail        `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"` // 司机列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`    // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverListRes) Reset() {
	*x = GetDriverListRes{}
	mi := &file_driver_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverListRes) ProtoMessage() {}

func (x *GetDriverListRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverListRes.ProtoReflect.Descriptor instead.
func (*GetDriverListRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDriverListRes) GetDrivers() []*DriverDetail {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *GetDriverListRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetDriverByIdReq 根据 ID 获取司机信息请求
type GetDriverByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      uint32                 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"` // 司机 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverByIdReq) Reset() {
	*x = GetDriverByIdReq{}
	mi := &file_driver_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverByIdReq) ProtoMessage() {}

func (x *GetDriverByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverByIdReq.ProtoReflect.Descriptor instead.
func (*GetDriverByIdReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDriverByIdReq) GetDriverId() uint32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

// GetDriverByIdRes 根据 ID 获取司机信息响应
type GetDriverByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        *DriverDetail          `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"` // 司机信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverByIdRes) Reset() {
	*x = GetDriverByIdRes{}
	mi := &file_driver_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverByIdRes) ProtoMessage() {}

func (x *GetDriverByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverByIdRes.ProtoReflect.Descriptor instead.
func (*GetDriverByIdRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDriverByIdRes) GetDriver() *DriverDetail {
	if x != nil {
		return x.Driver
	}
	return nil
}

// GetAvailableDriversReq 获取可服务司机请求
type GetAvailableDriversReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`                       // 乘客位置纬度
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`                       // 乘客位置经度
	Radius        float64                `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`                 // 搜索半径（公里）
	CarType       int32                  `protobuf:"varint,4,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"` // 车型类型（0-不限，1-经济型，2-舒适型，3-豪华型）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableDriversReq) Reset() {
	*x = GetAvailableDriversReq{}
	mi := &file_driver_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableDriversReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableDriversReq) ProtoMessage() {}

func (x *GetAvailableDriversReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableDriversReq.ProtoReflect.Descriptor instead.
func (*GetAvailableDriversReq) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvailableDriversReq) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetAvailableDriversReq) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *GetAvailableDriversReq) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *GetAvailableDriversReq) GetCarType() int32 {
	if x != nil {
		return x.CarType
	}
	return 0
}

// GetAvailableDriversRes 获取可服务司机响应
type GetAvailableDriversRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*DriverDetail        `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"` // 可服务司机列表
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`    // 司机数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableDriversRes) Reset() {
	*x = GetAvailableDriversRes{}
	mi := &file_driver_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableDriversRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableDriversRes) ProtoMessage() {}

func (x *GetAvailableDriversRes) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableDriversRes.ProtoReflect.Descriptor instead.
func (*GetAvailableDriversRes) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAvailableDriversRes) GetDrivers() []*DriverDetail {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *GetAvailableDriversRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// DriverDetail 司机详细信息
type DriverDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // 司机 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // 司机姓名
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`                                      // 手机号
	LicenseNo     string                 `protobuf:"bytes,4,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`             // 驾驶证号
	PlateNo       string                 `protobuf:"bytes,5,opt,name=plate_no,json=plateNo,proto3" json:"plate_no,omitempty"`                   // 车牌号
	CarType       int32                  `protobuf:"varint,6,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`                  // 车型类型（1-经济型，2-舒适型，3-豪华型）
	CarColor      string                 `protobuf:"bytes,7,opt,name=car_color,json=carColor,proto3" json:"car_color,omitempty"`                // 车辆颜色
	CarBrand      string                 `protobuf:"bytes,8,opt,name=car_brand,json=carBrand,proto3" json:"car_brand,omitempty"`                // 车辆品牌
	Lat           float64                `protobuf:"fixed64,9,opt,name=lat,proto3" json:"lat,omitempty"`                                        // 当前位置纬度
	Lng           float64                `protobuf:"fixed64,10,opt,name=lng,proto3" json:"lng,omitempty"`                                       // 当前位置经度
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                  // 状态（0-空闲，1-服务中，2-下线）
	ServiceScore  float64                `protobuf:"fixed64,12,opt,name=service_score,json=serviceScore,proto3" json:"service_score,omitempty"` // 服务评分
	TotalOrders   int32                  `protobuf:"varint,13,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`     // 总订单数
	CreatedAt     int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`           // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDetail) Reset() {
	*x = DriverDetail{}
	mi := &file_driver_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDetail) ProtoMessage() {}

func (x *DriverDetail) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDetail.ProtoReflect.Descriptor instead.
func (*DriverDetail) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_rawDescGZIP(), []int{8}
}

func (x *DriverDetail) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverDetail) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *DriverDetail) GetPlateNo() string {
	if x != nil {
		return x.PlateNo
	}
	return ""
}

func (x *DriverDetail) GetCarType() int32 {
	if x != nil {
		return x.CarType
	}
	return 0
}

func (x *DriverDetail) GetCarColor() string {
	if x != nil {
		return x.CarColor
	}
	return ""
}

func (x *DriverDetail) GetCarBrand() string {
	if x != nil {
		return x.CarBrand
	}
	return ""
}

func (x *DriverDetail) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *DriverDetail) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *DriverDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DriverDetail) GetServiceScore() float64 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *DriverDetail) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *DriverDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DriverDetail) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_driver_service_proto protoreflect.FileDescriptor

const file_driver_service_proto_rawDesc = "" +
	"\n" +
	"\x14driver_service.proto\x12\vdriverProto\"r\n" +
	"\x17UpdateDriverLocationReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\rR\bdriverId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"l\n" +
	"\x17UpdateDriverLocationRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"[\n" +
	"\x10GetDriverListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"]\n" +
	"\x10GetDriverListRes\x123\n" +
	"\adrivers\x18\x01 \x03(\v2\x19.driverProto.DriverDetailR\adrivers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"/\n" +
	"\x10GetDriverByIdReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\rR\bdriverId\"E\n" +
	"\x10GetDriverByIdRes\x121\n" +
	"\x06driver\x18\x01 \x01(\v2\x19.driverProto.DriverDetailR\x06driver\"o\n" +
	"\x16GetAvailableDriversReq\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x01R\x06radius\x12\x19\n" +
	"\bcar_type\x18\x04 \x01(\x05R\acarType\"c\n" +
	"\x16GetAvailableDriversRes\x123\n" +
	"\adrivers\x18\x01 \x03(\v2\x19.driverProto.DriverDetailR\adrivers\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x99\x03\n" +
	"\fDriverDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"license_no\x18\x04 \x01(\tR\tlicenseNo\x12\x19\n" +
	"\bplate_no\x18\x05 \x01(\tR\aplateNo\x12\x19\n" +
	"\bcar_type\x18\x06 \x01(\x05R\acarType\x12\x1b\n" +
	"\tcar_color\x18\a \x01(\tR\bcarColor\x12\x1b\n" +
	"\tcar_brand\x18\b \x01(\tR\bcarBrand\x12\x10\n" +
	"\x03lat\x18\t \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\n" +
	" \x01(\x01R\x03lng\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12#\n" +
	"\rservice_score\x18\f \x01(\x01R\fserviceScore\x12!\n" +
	"\ftotal_orders\x18\r \x01(\x05R\vtotalOrders\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt2\xf0\x02\n" +
	"\n" +
	"DriverInfo\x12M\n" +
	"\rGetDriverList\x12\x1d.driverProto.GetDriverListReq\x1a\x1d.driverProto.GetDriverListRes\x12M\n" +
	"\rGetDriverById\x12\x1d.driverProto.GetDriverByIdReq\x1a\x1d.driverProto.GetDriverByIdRes\x12_\n" +
	"\x13GetAvailableDrivers\x12#.driverProto.GetAvailableDriversReq\x1a#.driverProto.GetAvailableDriversRes\x12c\n" +
	"\x15UpdateDrixverLocation\x12$.driverProto.UpdateDriverLocationReq\x1a$.driverProto.UpdateDriverLocationResB\x12Z\x10./driver_serviceb\x06proto3"

var (
	file_driver_service_proto_rawDescOnce sync.Once
	file_driver_service_proto_rawDescData []byte
)

func file_driver_service_proto_rawDescGZIP() []byte {
	file_driver_service_proto_rawDescOnce.Do(func() {
		file_driver_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_service_proto_rawDesc), len(file_driver_service_proto_rawDesc)))
	})
	return file_driver_service_proto_rawDescData
}

var file_driver_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_driver_service_proto_goTypes = []any{
	(*UpdateDriverLocationReq)(nil), // 0: driverProto.UpdateDriverLocationReq
	(*UpdateDriverLocationRes)(nil), // 1: driverProto.UpdateDriverLocationRes
	(*GetDriverListReq)(nil),        // 2: driverProto.GetDriverListReq
	(*GetDriverListRes)(nil),        // 3: driverProto.GetDriverListRes
	(*GetDriverByIdReq)(nil),        // 4: driverProto.GetDriverByIdReq
	(*GetDriverByIdRes)(nil),        // 5: driverProto.GetDriverByIdRes
	(*GetAvailableDriversReq)(nil),  // 6: driverProto.GetAvailableDriversReq
	(*GetAvailableDriversRes)(nil),  // 7: driverProto.GetAvailableDriversRes
	(*DriverDetail)(nil),            // 8: driverProto.DriverDetail
}
var file_driver_service_proto_depIdxs = []int32{
	8, // 0: driverProto.GetDriverListRes.drivers:type_name -> driverProto.DriverDetail
	8, // 1: driverProto.GetDriverByIdRes.driver:type_name -> driverProto.DriverDetail
	8, // 2: driverProto.GetAvailableDriversRes.drivers:type_name -> driverProto.DriverDetail
	2, // 3: driverProto.DriverInfo.GetDriverList:input_type -> driverProto.GetDriverListReq
	4, // 4: driverProto.DriverInfo.GetDriverById:input_type -> driverProto.GetDriverByIdReq
	6, // 5: driverProto.DriverInfo.GetAvailableDrivers:input_type -> driverProto.GetAvailableDriversReq
	0, // 6: driverProto.DriverInfo.UpdateDrixverLocation:input_type -> driverProto.UpdateDriverLocationReq
	3, // 7: driverProto.DriverInfo.GetDriverList:output_type -> driverProto.GetDriverListRes
	5, // 8: driverProto.DriverInfo.GetDriverById:output_type -> driverProto.GetDriverByIdRes
	7, // 9: driverProto.DriverInfo.GetAvailableDrivers:output_type -> driverProto.GetAvailableDriversRes
	1, // 10: driverProto.DriverInfo.UpdateDrixverLocation:output_type -> driverProto.UpdateDriverLocationRes
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_driver_service_proto_init() }
func file_driver_service_proto_init() {
	if File_driver_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_service_proto_rawDesc), len(file_driver_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_service_proto_goTypes,
		DependencyIndexes: file_driver_service_proto_depIdxs,
		MessageInfos:      file_driver_service_proto_msgTypes,
	}.Build()
	File_driver_service_proto = out.File
	file_driver_service_proto_goTypes = nil
	file_driver_service_proto_depIdxs = nil
}
