//*
// ============================================
// 价格计算 Proto 定义
// ============================================
// 定义价格计算服务的请求和响应结构
// 用于 gRPC 通信
// ============================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: pricing_service.proto

package pricing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 计价规则配置
type PricingRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                   // 规则ID
	Name            string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                // 规则名称（如"标准计价"）
	BasePrice       float64 `protobuf:"fixed64,3,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`                   // 起步价（元）
	BaseKm          float64 `protobuf:"fixed64,4,opt,name=base_km,json=baseKm,proto3" json:"base_km,omitempty"`                            // 起步公里数
	PricePerKm      float64 `protobuf:"fixed64,5,opt,name=price_per_km,json=pricePerKm,proto3" json:"price_per_km,omitempty"`              // 每公里单价（元）
	PricePerMin     float64 `protobuf:"fixed64,6,opt,name=price_per_min,json=pricePerMin,proto3" json:"price_per_min,omitempty"`           // 每分钟单价（元）
	NightMultiplier float64 `protobuf:"fixed64,7,opt,name=night_multiplier,json=nightMultiplier,proto3" json:"night_multiplier,omitempty"` // 夜间倍数
	NightStartHour  int32   `protobuf:"varint,8,opt,name=night_start_hour,json=nightStartHour,proto3" json:"night_start_hour,omitempty"`   // 夜间开始时间（小时）
	NightEndHour    int32   `protobuf:"varint,9,opt,name=night_end_hour,json=nightEndHour,proto3" json:"night_end_hour,omitempty"`         // 夜间结束时间（小时）
}

func (x *PricingRule) Reset() {
	*x = PricingRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PricingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRule) ProtoMessage() {}

func (x *PricingRule) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRule.ProtoReflect.Descriptor instead.
func (*PricingRule) Descriptor() ([]byte, []int) {
	return file_pricing_service_proto_rawDescGZIP(), []int{0}
}

func (x *PricingRule) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PricingRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PricingRule) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *PricingRule) GetBaseKm() float64 {
	if x != nil {
		return x.BaseKm
	}
	return 0
}

func (x *PricingRule) GetPricePerKm() float64 {
	if x != nil {
		return x.PricePerKm
	}
	return 0
}

func (x *PricingRule) GetPricePerMin() float64 {
	if x != nil {
		return x.PricePerMin
	}
	return 0
}

func (x *PricingRule) GetNightMultiplier() float64 {
	if x != nil {
		return x.NightMultiplier
	}
	return 0
}

func (x *PricingRule) GetNightStartHour() int32 {
	if x != nil {
		return x.NightStartHour
	}
	return 0
}

func (x *PricingRule) GetNightEndHour() int32 {
	if x != nil {
		return x.NightEndHour
	}
	return 0
}

// 价格计算请求
type CalculatePriceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance float64 `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`          // 距离（公里）
	Duration int32   `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`           // 时长（秒）
	RuleId   int32   `protobuf:"varint,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"` // 计价规则ID（0表示使用默认规则）
}

func (x *CalculatePriceReq) Reset() {
	*x = CalculatePriceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatePriceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceReq) ProtoMessage() {}

func (x *CalculatePriceReq) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceReq.ProtoReflect.Descriptor instead.
func (*CalculatePriceReq) Descriptor() ([]byte, []int) {
	return file_pricing_service_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePriceReq) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *CalculatePriceReq) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CalculatePriceReq) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

// 价格计算响应
type CalculatePriceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasePrice     float64 `protobuf:"fixed64,1,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`             // 起步价
	DistancePrice float64 `protobuf:"fixed64,2,opt,name=distance_price,json=distancePrice,proto3" json:"distance_price,omitempty"` // 里程费
	TimePrice     float64 `protobuf:"fixed64,3,opt,name=time_price,json=timePrice,proto3" json:"time_price,omitempty"`             // 时长费
	NightFee      float64 `protobuf:"fixed64,4,opt,name=night_fee,json=nightFee,proto3" json:"night_fee,omitempty"`                // 夜间服务费
	TotalPrice    float64 `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`          // 总价
	RuleName      string  `protobuf:"bytes,6,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`                  // 使用的规则名称
	Success       bool    `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`                                   // 是否成功
	Message       string  `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`                                    // 消息
}

func (x *CalculatePriceRes) Reset() {
	*x = CalculatePriceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatePriceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceRes) ProtoMessage() {}

func (x *CalculatePriceRes) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceRes.ProtoReflect.Descriptor instead.
func (*CalculatePriceRes) Descriptor() ([]byte, []int) {
	return file_pricing_service_proto_rawDescGZIP(), []int{2}
}

func (x *CalculatePriceRes) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *CalculatePriceRes) GetDistancePrice() float64 {
	if x != nil {
		return x.DistancePrice
	}
	return 0
}

func (x *CalculatePriceRes) GetTimePrice() float64 {
	if x != nil {
		return x.TimePrice
	}
	return 0
}

func (x *CalculatePriceRes) GetNightFee() float64 {
	if x != nil {
		return x.NightFee
	}
	return 0
}

func (x *CalculatePriceRes) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CalculatePriceRes) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *CalculatePriceRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CalculatePriceRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取所有计价规则请求
type GetRulesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRulesReq) Reset() {
	*x = GetRulesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRulesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesReq) ProtoMessage() {}

func (x *GetRulesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesReq.ProtoReflect.Descriptor instead.
func (*GetRulesReq) Descriptor() ([]byte, []int) {
	return file_pricing_service_proto_rawDescGZIP(), []int{3}
}

// 获取所有计价规则响应
type GetRulesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules   []*PricingRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Success bool           `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetRulesRes) Reset() {
	*x = GetRulesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRulesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesRes) ProtoMessage() {}

func (x *GetRulesRes) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesRes.ProtoReflect.Descriptor instead.
func (*GetRulesRes) Descriptor() ([]byte, []int) {
	return file_pricing_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetRulesRes) GetRules() []*PricingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *GetRulesRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRulesRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pricing_service_proto protoreflect.FileDescriptor

var file_pricing_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x02, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e,
	0x67, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x62,
	0x61, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x6b, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x62, 0x61, 0x73, 0x65, 0x4b,
	0x6d, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x6b,
	0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65,
	0x72, 0x4b, 0x6d, 0x12, 0x22, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72,
	0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x50, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x6e, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0f, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69,
	0x65, 0x72, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6e, 0x69,
	0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x24, 0x0a, 0x0e,
	0x6e, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x45, 0x6e, 0x64, 0x48, 0x6f,
	0x75, 0x72, 0x22, 0x64, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x87, 0x02, 0x0a, 0x11, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x66, 0x65, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x46, 0x65, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x22, 0x72, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x12, 0x2f, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xa6, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0e, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x69,
	0x63, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x72,
	0x69, 0x63, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x69,
	0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x42, 0x2b,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x62,
	0x65, 0x69, 0x77, 0x61, 0x6e, 0x6a, 0x69, 0x61, 0x2f, 0x72, 0x69, 0x64, 0x65, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pricing_service_proto_rawDescOnce sync.Once
	file_pricing_service_proto_rawDescData = file_pricing_service_proto_rawDesc
)

func file_pricing_service_proto_rawDescGZIP() []byte {
	file_pricing_service_proto_rawDescOnce.Do(func() {
		file_pricing_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pricing_service_proto_rawDescData)
	})
	return file_pricing_service_proto_rawDescData
}

var file_pricing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pricing_service_proto_goTypes = []any{
	(*PricingRule)(nil),       // 0: pricingProto.PricingRule
	(*CalculatePriceReq)(nil), // 1: pricingProto.CalculatePriceReq
	(*CalculatePriceRes)(nil), // 2: pricingProto.CalculatePriceRes
	(*GetRulesReq)(nil),       // 3: pricingProto.GetRulesReq
	(*GetRulesRes)(nil),       // 4: pricingProto.GetRulesRes
}
var file_pricing_service_proto_depIdxs = []int32{
	0, // 0: pricingProto.GetRulesRes.rules:type_name -> pricingProto.PricingRule
	1, // 1: pricingProto.PricingService.CalculatePrice:input_type -> pricingProto.CalculatePriceReq
	3, // 2: pricingProto.PricingService.GetRules:input_type -> pricingProto.GetRulesReq
	2, // 3: pricingProto.PricingService.CalculatePrice:output_type -> pricingProto.CalculatePriceRes
	4, // 4: pricingProto.PricingService.GetRules:output_type -> pricingProto.GetRulesRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pricing_service_proto_init() }
func file_pricing_service_proto_init() {
	if File_pricing_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pricing_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PricingRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CalculatePriceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CalculatePriceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetRulesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetRulesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pricing_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pricing_service_proto_goTypes,
		DependencyIndexes: file_pricing_service_proto_depIdxs,
		MessageInfos:      file_pricing_service_proto_msgTypes,
	}.Build()
	File_pricing_service_proto = out.File
	file_pricing_service_proto_rawDesc = nil
	file_pricing_service_proto_goTypes = nil
	file_pricing_service_proto_depIdxs = nil
}
