//*
// ============================================
// 价格计算 Proto 定义
// ============================================
// 定义价格计算服务的请求和响应结构
// 用于 gRPC 通信
// ============================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: pricing_service.proto

package pricing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PricingService_CalculatePrice_FullMethodName = "/pricingProto.PricingService/CalculatePrice"
	PricingService_GetRules_FullMethodName       = "/pricingProto.PricingService/GetRules"
)

// PricingServiceClient is the client API for PricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// PricingService 价格计算服务
// 提供价格计算和计价规则管理功能
type PricingServiceClient interface {
	// 计算价格
	CalculatePrice(ctx context.Context, in *CalculatePriceReq, opts ...grpc.CallOption) (*CalculatePriceRes, error)
	// 获取所有计价规则
	GetRules(ctx context.Context, in *GetRulesReq, opts ...grpc.CallOption) (*GetRulesRes, error)
}

type pricingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingServiceClient(cc grpc.ClientConnInterface) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) CalculatePrice(ctx context.Context, in *CalculatePriceReq, opts ...grpc.CallOption) (*CalculatePriceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePriceRes)
	err := c.cc.Invoke(ctx, PricingService_CalculatePrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) GetRules(ctx context.Context, in *GetRulesReq, opts ...grpc.CallOption) (*GetRulesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRulesRes)
	err := c.cc.Invoke(ctx, PricingService_GetRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServiceServer is the server API for PricingService service.
// All implementations must embed UnimplementedPricingServiceServer
// for forward compatibility
//
// *
// PricingService 价格计算服务
// 提供价格计算和计价规则管理功能
type PricingServiceServer interface {
	// 计算价格
	CalculatePrice(context.Context, *CalculatePriceReq) (*CalculatePriceRes, error)
	// 获取所有计价规则
	GetRules(context.Context, *GetRulesReq) (*GetRulesRes, error)
	mustEmbedUnimplementedPricingServiceServer()
}

// UnimplementedPricingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPricingServiceServer struct {
}

func (UnimplementedPricingServiceServer) CalculatePrice(context.Context, *CalculatePriceReq) (*CalculatePriceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePrice not implemented")
}
func (UnimplementedPricingServiceServer) GetRules(context.Context, *GetRulesReq) (*GetRulesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRules not implemented")
}
func (UnimplementedPricingServiceServer) mustEmbedUnimplementedPricingServiceServer() {}

// UnsafePricingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PricingServiceServer will
// result in compilation errors.
type UnsafePricingServiceServer interface {
	mustEmbedUnimplementedPricingServiceServer()
}

func RegisterPricingServiceServer(s grpc.ServiceRegistrar, srv PricingServiceServer) {
	s.RegisterService(&PricingService_ServiceDesc, srv)
}

func _PricingService_CalculatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePriceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).CalculatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_CalculatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).CalculatePrice(ctx, req.(*CalculatePriceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_GetRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRulesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetRules(ctx, req.(*GetRulesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PricingService_ServiceDesc is the grpc.ServiceDesc for PricingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PricingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pricingProto.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatePrice",
			Handler:    _PricingService_CalculatePrice_Handler,
		},
		{
			MethodName: "GetRules",
			Handler:    _PricingService_GetRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricing_service.proto",
}
