// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: dispatch_service.proto

package dispatch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dispatch_DispatchOrder_FullMethodName     = "/dispatchProto.Dispatch/DispatchOrder"
	Dispatch_GetDispatchStatus_FullMethodName = "/dispatchProto.Dispatch/GetDispatchStatus"
	Dispatch_CancelDispatch_FullMethodName    = "/dispatchProto.Dispatch/CancelDispatch"
	Dispatch_ForceDispatch_FullMethodName     = "/dispatchProto.Dispatch/ForceDispatch"
	Dispatch_ManualDispatch_FullMethodName    = "/dispatchProto.Dispatch/ManualDispatch"
	Dispatch_DriverRejectOrder_FullMethodName = "/dispatchProto.Dispatch/DriverRejectOrder"
)

// DispatchClient is the client API for Dispatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatchClient interface {
	DispatchOrder(ctx context.Context, in *DispatchOrderReq, opts ...grpc.CallOption) (*DispatchOrderRes, error)
	GetDispatchStatus(ctx context.Context, in *GetDispatchStatusReq, opts ...grpc.CallOption) (*GetDispatchStatusRes, error)
	CancelDispatch(ctx context.Context, in *CancelDispatchReq, opts ...grpc.CallOption) (*CancelDispatchRes, error)
	ForceDispatch(ctx context.Context, in *ForceDispatchRequest, opts ...grpc.CallOption) (*ForceDispatchResponse, error)
	ManualDispatch(ctx context.Context, in *ManualDispatchRequest, opts ...grpc.CallOption) (*ManualDispatchResponse, error)
	DriverRejectOrder(ctx context.Context, in *DriverRejectOrderRequest, opts ...grpc.CallOption) (*DriverRejectOrderResponse, error)
}

type dispatchClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchClient(cc grpc.ClientConnInterface) DispatchClient {
	return &dispatchClient{cc}
}

func (c *dispatchClient) DispatchOrder(ctx context.Context, in *DispatchOrderReq, opts ...grpc.CallOption) (*DispatchOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchOrderRes)
	err := c.cc.Invoke(ctx, Dispatch_DispatchOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) GetDispatchStatus(ctx context.Context, in *GetDispatchStatusReq, opts ...grpc.CallOption) (*GetDispatchStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDispatchStatusRes)
	err := c.cc.Invoke(ctx, Dispatch_GetDispatchStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) CancelDispatch(ctx context.Context, in *CancelDispatchReq, opts ...grpc.CallOption) (*CancelDispatchRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelDispatchRes)
	err := c.cc.Invoke(ctx, Dispatch_CancelDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) ForceDispatch(ctx context.Context, in *ForceDispatchRequest, opts ...grpc.CallOption) (*ForceDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceDispatchResponse)
	err := c.cc.Invoke(ctx, Dispatch_ForceDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) ManualDispatch(ctx context.Context, in *ManualDispatchRequest, opts ...grpc.CallOption) (*ManualDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManualDispatchResponse)
	err := c.cc.Invoke(ctx, Dispatch_ManualDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) DriverRejectOrder(ctx context.Context, in *DriverRejectOrderRequest, opts ...grpc.CallOption) (*DriverRejectOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverRejectOrderResponse)
	err := c.cc.Invoke(ctx, Dispatch_DriverRejectOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServer is the server API for Dispatch service.
// All implementations must embed UnimplementedDispatchServer
// for forward compatibility.
type DispatchServer interface {
	DispatchOrder(context.Context, *DispatchOrderReq) (*DispatchOrderRes, error)
	GetDispatchStatus(context.Context, *GetDispatchStatusReq) (*GetDispatchStatusRes, error)
	CancelDispatch(context.Context, *CancelDispatchReq) (*CancelDispatchRes, error)
	ForceDispatch(context.Context, *ForceDispatchRequest) (*ForceDispatchResponse, error)
	ManualDispatch(context.Context, *ManualDispatchRequest) (*ManualDispatchResponse, error)
	DriverRejectOrder(context.Context, *DriverRejectOrderRequest) (*DriverRejectOrderResponse, error)
	mustEmbedUnimplementedDispatchServer()
}

// UnimplementedDispatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispatchServer struct{}

func (UnimplementedDispatchServer) DispatchOrder(context.Context, *DispatchOrderReq) (*DispatchOrderRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchOrder not implemented")
}
func (UnimplementedDispatchServer) GetDispatchStatus(context.Context, *GetDispatchStatusReq) (*GetDispatchStatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDispatchStatus not implemented")
}
func (UnimplementedDispatchServer) CancelDispatch(context.Context, *CancelDispatchReq) (*CancelDispatchRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelDispatch not implemented")
}
func (UnimplementedDispatchServer) ForceDispatch(context.Context, *ForceDispatchRequest) (*ForceDispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceDispatch not implemented")
}
func (UnimplementedDispatchServer) ManualDispatch(context.Context, *ManualDispatchRequest) (*ManualDispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ManualDispatch not implemented")
}
func (UnimplementedDispatchServer) DriverRejectOrder(context.Context, *DriverRejectOrderRequest) (*DriverRejectOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverRejectOrder not implemented")
}
func (UnimplementedDispatchServer) mustEmbedUnimplementedDispatchServer() {}
func (UnimplementedDispatchServer) testEmbeddedByValue()                  {}

// UnsafeDispatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServer will
// result in compilation errors.
type UnsafeDispatchServer interface {
	mustEmbedUnimplementedDispatchServer()
}

func RegisterDispatchServer(s grpc.ServiceRegistrar, srv DispatchServer) {
	// If the following call panics, it indicates UnimplementedDispatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dispatch_ServiceDesc, srv)
}

func _Dispatch_DispatchOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).DispatchOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_DispatchOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).DispatchOrder(ctx, req.(*DispatchOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_GetDispatchStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDispatchStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).GetDispatchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_GetDispatchStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).GetDispatchStatus(ctx, req.(*GetDispatchStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_CancelDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelDispatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).CancelDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_CancelDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).CancelDispatch(ctx, req.(*CancelDispatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_ForceDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).ForceDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_ForceDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).ForceDispatch(ctx, req.(*ForceDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_ManualDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).ManualDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_ManualDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).ManualDispatch(ctx, req.(*ManualDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_DriverRejectOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverRejectOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).DriverRejectOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_DriverRejectOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).DriverRejectOrder(ctx, req.(*DriverRejectOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dispatch_ServiceDesc is the grpc.ServiceDesc for Dispatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dispatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dispatchProto.Dispatch",
	HandlerType: (*DispatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchOrder",
			Handler:    _Dispatch_DispatchOrder_Handler,
		},
		{
			MethodName: "GetDispatchStatus",
			Handler:    _Dispatch_GetDispatchStatus_Handler,
		},
		{
			MethodName: "CancelDispatch",
			Handler:    _Dispatch_CancelDispatch_Handler,
		},
		{
			MethodName: "ForceDispatch",
			Handler:    _Dispatch_ForceDispatch_Handler,
		},
		{
			MethodName: "ManualDispatch",
			Handler:    _Dispatch_ManualDispatch_Handler,
		},
		{
			MethodName: "DriverRejectOrder",
			Handler:    _Dispatch_DriverRejectOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatch_service.proto",
}
