// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: driver_notify_service.proto

package driver_notify

import (
	context "context"
	ride "github.com/cibeiwanjia/ride-proto/ride"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifyService_PushToDriver_FullMethodName           = "/driver_notify.NotifyService/PushToDriver"
	NotifyService_UpdateDriverLocation_FullMethodName   = "/driver_notify.NotifyService/UpdateDriverLocation"
	NotifyService_CreateRideSharingOrder_FullMethodName = "/driver_notify.NotifyService/CreateRideSharingOrder"
	NotifyService_GetDriverOrders_FullMethodName        = "/driver_notify.NotifyService/GetDriverOrders"
	NotifyService_DriverAccept_FullMethodName           = "/driver_notify.NotifyService/DriverAccept"
	NotifyService_GetNotifyRecord_FullMethodName        = "/driver_notify.NotifyService/GetNotifyRecord"
	NotifyService_NotifyTripStatus_FullMethodName       = "/driver_notify.NotifyService/NotifyTripStatus"
	NotifyService_NotifyPaymentResult_FullMethodName    = "/driver_notify.NotifyService/NotifyPaymentResult"
)

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifyServiceClient interface {
	// 推送通知
	PushToDriver(ctx context.Context, in *PushNotifyReq, opts ...grpc.CallOption) (*PushNotifyRes, error)
	// 更新司机位置
	UpdateDriverLocation(ctx context.Context, in *UpdateDriverLocationReq, opts ...grpc.CallOption) (*UpdateDriverLocationRes, error)
	// 创建顺风车订单
	CreateRideSharingOrder(ctx context.Context, in *CreateRideSharingOrderReq, opts ...grpc.CallOption) (*CreateRideSharingOrderRes, error)
	// 获取司机订单
	GetDriverOrders(ctx context.Context, in *GetDriverOrdersReq, opts ...grpc.CallOption) (*GetDriverOrdersRes, error)
	// 司机接单
	DriverAccept(ctx context.Context, in *ride.DriverAcceptReq, opts ...grpc.CallOption) (*ride.DriverAcceptRes, error)
	// 获取通知记录
	GetNotifyRecord(ctx context.Context, in *GetNotifyRecordReq, opts ...grpc.CallOption) (*GetNotifyRecordRes, error)
	// 行程状态通知
	NotifyTripStatus(ctx context.Context, in *ride.TripStatusUpdateReq, opts ...grpc.CallOption) (*ride.TripStatusUpdateRes, error)
	// 支付结果通知
	NotifyPaymentResult(ctx context.Context, in *ride.PaymentResultCallbackReq, opts ...grpc.CallOption) (*ride.PaymentResultCallbackRes, error)
}

type notifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServiceClient(cc grpc.ClientConnInterface) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) PushToDriver(ctx context.Context, in *PushNotifyReq, opts ...grpc.CallOption) (*PushNotifyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushNotifyRes)
	err := c.cc.Invoke(ctx, NotifyService_PushToDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) UpdateDriverLocation(ctx context.Context, in *UpdateDriverLocationReq, opts ...grpc.CallOption) (*UpdateDriverLocationRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDriverLocationRes)
	err := c.cc.Invoke(ctx, NotifyService_UpdateDriverLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateRideSharingOrder(ctx context.Context, in *CreateRideSharingOrderReq, opts ...grpc.CallOption) (*CreateRideSharingOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRideSharingOrderRes)
	err := c.cc.Invoke(ctx, NotifyService_CreateRideSharingOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetDriverOrders(ctx context.Context, in *GetDriverOrdersReq, opts ...grpc.CallOption) (*GetDriverOrdersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverOrdersRes)
	err := c.cc.Invoke(ctx, NotifyService_GetDriverOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) DriverAccept(ctx context.Context, in *ride.DriverAcceptReq, opts ...grpc.CallOption) (*ride.DriverAcceptRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ride.DriverAcceptRes)
	err := c.cc.Invoke(ctx, NotifyService_DriverAccept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetNotifyRecord(ctx context.Context, in *GetNotifyRecordReq, opts ...grpc.CallOption) (*GetNotifyRecordRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotifyRecordRes)
	err := c.cc.Invoke(ctx, NotifyService_GetNotifyRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) NotifyTripStatus(ctx context.Context, in *ride.TripStatusUpdateReq, opts ...grpc.CallOption) (*ride.TripStatusUpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ride.TripStatusUpdateRes)
	err := c.cc.Invoke(ctx, NotifyService_NotifyTripStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) NotifyPaymentResult(ctx context.Context, in *ride.PaymentResultCallbackReq, opts ...grpc.CallOption) (*ride.PaymentResultCallbackRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ride.PaymentResultCallbackRes)
	err := c.cc.Invoke(ctx, NotifyService_NotifyPaymentResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
// All implementations must embed UnimplementedNotifyServiceServer
// for forward compatibility.
type NotifyServiceServer interface {
	// 推送通知
	PushToDriver(context.Context, *PushNotifyReq) (*PushNotifyRes, error)
	// 更新司机位置
	UpdateDriverLocation(context.Context, *UpdateDriverLocationReq) (*UpdateDriverLocationRes, error)
	// 创建顺风车订单
	CreateRideSharingOrder(context.Context, *CreateRideSharingOrderReq) (*CreateRideSharingOrderRes, error)
	// 获取司机订单
	GetDriverOrders(context.Context, *GetDriverOrdersReq) (*GetDriverOrdersRes, error)
	// 司机接单
	DriverAccept(context.Context, *ride.DriverAcceptReq) (*ride.DriverAcceptRes, error)
	// 获取通知记录
	GetNotifyRecord(context.Context, *GetNotifyRecordReq) (*GetNotifyRecordRes, error)
	// 行程状态通知
	NotifyTripStatus(context.Context, *ride.TripStatusUpdateReq) (*ride.TripStatusUpdateRes, error)
	// 支付结果通知
	NotifyPaymentResult(context.Context, *ride.PaymentResultCallbackReq) (*ride.PaymentResultCallbackRes, error)
	mustEmbedUnimplementedNotifyServiceServer()
}

// UnimplementedNotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifyServiceServer struct{}

func (UnimplementedNotifyServiceServer) PushToDriver(context.Context, *PushNotifyReq) (*PushNotifyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToDriver not implemented")
}
func (UnimplementedNotifyServiceServer) UpdateDriverLocation(context.Context, *UpdateDriverLocationReq) (*UpdateDriverLocationRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDriverLocation not implemented")
}
func (UnimplementedNotifyServiceServer) CreateRideSharingOrder(context.Context, *CreateRideSharingOrderReq) (*CreateRideSharingOrderRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRideSharingOrder not implemented")
}
func (UnimplementedNotifyServiceServer) GetDriverOrders(context.Context, *GetDriverOrdersReq) (*GetDriverOrdersRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverOrders not implemented")
}
func (UnimplementedNotifyServiceServer) DriverAccept(context.Context, *ride.DriverAcceptReq) (*ride.DriverAcceptRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverAccept not implemented")
}
func (UnimplementedNotifyServiceServer) GetNotifyRecord(context.Context, *GetNotifyRecordReq) (*GetNotifyRecordRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotifyRecord not implemented")
}
func (UnimplementedNotifyServiceServer) NotifyTripStatus(context.Context, *ride.TripStatusUpdateReq) (*ride.TripStatusUpdateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyTripStatus not implemented")
}
func (UnimplementedNotifyServiceServer) NotifyPaymentResult(context.Context, *ride.PaymentResultCallbackReq) (*ride.PaymentResultCallbackRes, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPaymentResult not implemented")
}
func (UnimplementedNotifyServiceServer) mustEmbedUnimplementedNotifyServiceServer() {}
func (UnimplementedNotifyServiceServer) testEmbeddedByValue()                       {}

// UnsafeNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServiceServer will
// result in compilation errors.
type UnsafeNotifyServiceServer interface {
	mustEmbedUnimplementedNotifyServiceServer()
}

func RegisterNotifyServiceServer(s grpc.ServiceRegistrar, srv NotifyServiceServer) {
	// If the following call panics, it indicates UnimplementedNotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifyService_ServiceDesc, srv)
}

func _NotifyService_PushToDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).PushToDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_PushToDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).PushToDriver(ctx, req.(*PushNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_UpdateDriverLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverLocationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).UpdateDriverLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_UpdateDriverLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).UpdateDriverLocation(ctx, req.(*UpdateDriverLocationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateRideSharingOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRideSharingOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateRideSharingOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateRideSharingOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateRideSharingOrder(ctx, req.(*CreateRideSharingOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetDriverOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetDriverOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetDriverOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetDriverOrders(ctx, req.(*GetDriverOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_DriverAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ride.DriverAcceptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).DriverAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_DriverAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).DriverAccept(ctx, req.(*ride.DriverAcceptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetNotifyRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifyRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetNotifyRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetNotifyRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetNotifyRecord(ctx, req.(*GetNotifyRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_NotifyTripStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ride.TripStatusUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).NotifyTripStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_NotifyTripStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).NotifyTripStatus(ctx, req.(*ride.TripStatusUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_NotifyPaymentResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ride.PaymentResultCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).NotifyPaymentResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_NotifyPaymentResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).NotifyPaymentResult(ctx, req.(*ride.PaymentResultCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifyService_ServiceDesc is the grpc.ServiceDesc for NotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver_notify.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushToDriver",
			Handler:    _NotifyService_PushToDriver_Handler,
		},
		{
			MethodName: "UpdateDriverLocation",
			Handler:    _NotifyService_UpdateDriverLocation_Handler,
		},
		{
			MethodName: "CreateRideSharingOrder",
			Handler:    _NotifyService_CreateRideSharingOrder_Handler,
		},
		{
			MethodName: "GetDriverOrders",
			Handler:    _NotifyService_GetDriverOrders_Handler,
		},
		{
			MethodName: "DriverAccept",
			Handler:    _NotifyService_DriverAccept_Handler,
		},
		{
			MethodName: "GetNotifyRecord",
			Handler:    _NotifyService_GetNotifyRecord_Handler,
		},
		{
			MethodName: "NotifyTripStatus",
			Handler:    _NotifyService_NotifyTripStatus_Handler,
		},
		{
			MethodName: "NotifyPaymentResult",
			Handler:    _NotifyService_NotifyPaymentResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver_notify_service.proto",
}
