// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: driver_notify_service.proto

package driver_notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	NotifyService_GetNotifyRecord_FullMethodName        = "/notifyProto.NotifyService/GetNotifyRecord"
	NotifyService_PushToDriver_FullMethodName           = "/notifyProto.NotifyService/PushToDriver"
	NotifyService_UpdateDriverLocation_FullMethodName   = "/notifyProto.NotifyService/UpdateDriverLocation"
	NotifyService_CreateRideSharingOrder_FullMethodName = "/notifyProto.NotifyService/CreateRideSharingOrder"
	NotifyService_GetDriverOrders_FullMethodName        = "/notifyProto.NotifyService/GetDriverOrders"
	NotifyService_DriverAccept_FullMethodName           = "/notifyProto.NotifyService/DriverAccept"
)

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 通知服务gRPC接口
type NotifyServiceClient interface {
	GetNotifyRecord(ctx context.Context, in *GetNotifyRecordReq, opts ...grpc.CallOption) (*GetNotifyRecordRes, error)
	PushToDriver(ctx context.Context, in *PushNotifyReq, opts ...grpc.CallOption) (*PushNotifyRes, error)
	UpdateDriverLocation(ctx context.Context, in *UpdateDriverLocationReq, opts ...grpc.CallOption) (*UpdateDriverLocationRes, error)
	CreateRideSharingOrder(ctx context.Context, in *CreateRideSharingOrderReq, opts ...grpc.CallOption) (*CreateRideSharingOrderRes, error)
	GetDriverOrders(ctx context.Context, in *GetDriverOrdersReq, opts ...grpc.CallOption) (*GetDriverOrdersRes, error)
	DriverAccept(ctx context.Context, in *DriverAcceptReq, opts ...grpc.CallOption) (*DriverAcceptRes, error)
}

type notifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServiceClient(cc grpc.ClientConnInterface) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) GetNotifyRecord(ctx context.Context, in *GetNotifyRecordReq, opts ...grpc.CallOption) (*GetNotifyRecordRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotifyRecordRes)
	err := c.cc.Invoke(ctx, NotifyService_GetNotifyRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) PushToDriver(ctx context.Context, in *PushNotifyReq, opts ...grpc.CallOption) (*PushNotifyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushNotifyRes)
	err := c.cc.Invoke(ctx, NotifyService_PushToDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) UpdateDriverLocation(ctx context.Context, in *UpdateDriverLocationReq, opts ...grpc.CallOption) (*UpdateDriverLocationRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDriverLocationRes)
	err := c.cc.Invoke(ctx, NotifyService_UpdateDriverLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateRideSharingOrder(ctx context.Context, in *CreateRideSharingOrderReq, opts ...grpc.CallOption) (*CreateRideSharingOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRideSharingOrderRes)
	err := c.cc.Invoke(ctx, NotifyService_CreateRideSharingOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetDriverOrders(ctx context.Context, in *GetDriverOrdersReq, opts ...grpc.CallOption) (*GetDriverOrdersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverOrdersRes)
	err := c.cc.Invoke(ctx, NotifyService_GetDriverOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) DriverAccept(ctx context.Context, in *DriverAcceptReq, opts ...grpc.CallOption) (*DriverAcceptRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverAcceptRes)
	err := c.cc.Invoke(ctx, NotifyService_DriverAccept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
// All implementations must embed UnimplementedNotifyServiceServer
// for forward compatibility
//
// 通知服务gRPC接口
type NotifyServiceServer interface {
	GetNotifyRecord(context.Context, *GetNotifyRecordReq) (*GetNotifyRecordRes, error)
	PushToDriver(context.Context, *PushNotifyReq) (*PushNotifyRes, error)
	UpdateDriverLocation(context.Context, *UpdateDriverLocationReq) (*UpdateDriverLocationRes, error)
	CreateRideSharingOrder(context.Context, *CreateRideSharingOrderReq) (*CreateRideSharingOrderRes, error)
	GetDriverOrders(context.Context, *GetDriverOrdersReq) (*GetDriverOrdersRes, error)
	DriverAccept(context.Context, *DriverAcceptReq) (*DriverAcceptRes, error)
	mustEmbedUnimplementedNotifyServiceServer()
}

// UnimplementedNotifyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotifyServiceServer struct {
}

func (UnimplementedNotifyServiceServer) GetNotifyRecord(context.Context, *GetNotifyRecordReq) (*GetNotifyRecordRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotifyRecord not implemented")
}
func (UnimplementedNotifyServiceServer) PushToDriver(context.Context, *PushNotifyReq) (*PushNotifyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToDriver not implemented")
}
func (UnimplementedNotifyServiceServer) UpdateDriverLocation(context.Context, *UpdateDriverLocationReq) (*UpdateDriverLocationRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDriverLocation not implemented")
}
func (UnimplementedNotifyServiceServer) CreateRideSharingOrder(context.Context, *CreateRideSharingOrderReq) (*CreateRideSharingOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRideSharingOrder not implemented")
}
func (UnimplementedNotifyServiceServer) GetDriverOrders(context.Context, *GetDriverOrdersReq) (*GetDriverOrdersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDriverOrders not implemented")
}
func (UnimplementedNotifyServiceServer) DriverAccept(context.Context, *DriverAcceptReq) (*DriverAcceptRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DriverAccept not implemented")
}
func (UnimplementedNotifyServiceServer) mustEmbedUnimplementedNotifyServiceServer() {}

// UnsafeNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServiceServer will
// result in compilation errors.
type UnsafeNotifyServiceServer interface {
	mustEmbedUnimplementedNotifyServiceServer()
}

func RegisterNotifyServiceServer(s grpc.ServiceRegistrar, srv NotifyServiceServer) {
	s.RegisterService(&NotifyService_ServiceDesc, srv)
}

func _NotifyService_GetNotifyRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifyRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetNotifyRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetNotifyRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetNotifyRecord(ctx, req.(*GetNotifyRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_PushToDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).PushToDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_PushToDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).PushToDriver(ctx, req.(*PushNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_UpdateDriverLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverLocationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).UpdateDriverLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_UpdateDriverLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).UpdateDriverLocation(ctx, req.(*UpdateDriverLocationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateRideSharingOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRideSharingOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateRideSharingOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateRideSharingOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateRideSharingOrder(ctx, req.(*CreateRideSharingOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetDriverOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetDriverOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetDriverOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetDriverOrders(ctx, req.(*GetDriverOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_DriverAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverAcceptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).DriverAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_DriverAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).DriverAccept(ctx, req.(*DriverAcceptReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifyService_ServiceDesc is the grpc.ServiceDesc for NotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifyProto.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotifyRecord",
			Handler:    _NotifyService_GetNotifyRecord_Handler,
		},
		{
			MethodName: "PushToDriver",
			Handler:    _NotifyService_PushToDriver_Handler,
		},
		{
			MethodName: "UpdateDriverLocation",
			Handler:    _NotifyService_UpdateDriverLocation_Handler,
		},
		{
			MethodName: "CreateRideSharingOrder",
			Handler:    _NotifyService_CreateRideSharingOrder_Handler,
		},
		{
			MethodName: "GetDriverOrders",
			Handler:    _NotifyService_GetDriverOrders_Handler,
		},
		{
			MethodName: "DriverAccept",
			Handler:    _NotifyService_DriverAccept_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver_notify_service.proto",
}
