// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: coupon_service.proto

package coupon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CouponServiceClient is the client API for CouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouponServiceClient interface {
	// 创建平台分发任务
	CreateDistributeTask(ctx context.Context, in *CreateDistributeTaskRequest, opts ...grpc.CallOption) (*CreateDistributeTaskResponse, error)
	// 执行平台分发任务
	ExecuteDistributeTask(ctx context.Context, in *ExecuteDistributeTaskRequest, opts ...grpc.CallOption) (*ExecuteDistributeTaskResponse, error)
	// 用户主动领券
	UserGetCoupon(ctx context.Context, in *UserGetCouponRequest, opts ...grpc.CallOption) (*UserGetCouponResponse, error)
}

type couponServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponServiceClient(cc grpc.ClientConnInterface) CouponServiceClient {
	return &couponServiceClient{cc}
}

func (c *couponServiceClient) CreateDistributeTask(ctx context.Context, in *CreateDistributeTaskRequest, opts ...grpc.CallOption) (*CreateDistributeTaskResponse, error) {
	out := new(CreateDistributeTaskResponse)
	err := c.cc.Invoke(ctx, "/couponProto.CouponService/CreateDistributeTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ExecuteDistributeTask(ctx context.Context, in *ExecuteDistributeTaskRequest, opts ...grpc.CallOption) (*ExecuteDistributeTaskResponse, error) {
	out := new(ExecuteDistributeTaskResponse)
	err := c.cc.Invoke(ctx, "/couponProto.CouponService/ExecuteDistributeTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) UserGetCoupon(ctx context.Context, in *UserGetCouponRequest, opts ...grpc.CallOption) (*UserGetCouponResponse, error) {
	out := new(UserGetCouponResponse)
	err := c.cc.Invoke(ctx, "/couponProto.CouponService/UserGetCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServiceServer is the server API for CouponService service.
// All implementations must embed UnimplementedCouponServiceServer
// for forward compatibility
type CouponServiceServer interface {
	// 创建平台分发任务
	CreateDistributeTask(context.Context, *CreateDistributeTaskRequest) (*CreateDistributeTaskResponse, error)
	// 执行平台分发任务
	ExecuteDistributeTask(context.Context, *ExecuteDistributeTaskRequest) (*ExecuteDistributeTaskResponse, error)
	// 用户主动领券
	UserGetCoupon(context.Context, *UserGetCouponRequest) (*UserGetCouponResponse, error)
	mustEmbedUnimplementedCouponServiceServer()
}

// UnimplementedCouponServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCouponServiceServer struct {
}

func (UnimplementedCouponServiceServer) CreateDistributeTask(context.Context, *CreateDistributeTaskRequest) (*CreateDistributeTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDistributeTask not implemented")
}
func (UnimplementedCouponServiceServer) ExecuteDistributeTask(context.Context, *ExecuteDistributeTaskRequest) (*ExecuteDistributeTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDistributeTask not implemented")
}
func (UnimplementedCouponServiceServer) UserGetCoupon(context.Context, *UserGetCouponRequest) (*UserGetCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetCoupon not implemented")
}
func (UnimplementedCouponServiceServer) mustEmbedUnimplementedCouponServiceServer() {}

// UnsafeCouponServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponServiceServer will
// result in compilation errors.
type UnsafeCouponServiceServer interface {
	mustEmbedUnimplementedCouponServiceServer()
}

func RegisterCouponServiceServer(s grpc.ServiceRegistrar, srv CouponServiceServer) {
	s.RegisterService(&CouponService_ServiceDesc, srv)
}

func _CouponService_CreateDistributeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDistributeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CreateDistributeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/couponProto.CouponService/CreateDistributeTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CreateDistributeTask(ctx, req.(*CreateDistributeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ExecuteDistributeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteDistributeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ExecuteDistributeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/couponProto.CouponService/ExecuteDistributeTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ExecuteDistributeTask(ctx, req.(*ExecuteDistributeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_UserGetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).UserGetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/couponProto.CouponService/UserGetCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).UserGetCoupon(ctx, req.(*UserGetCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CouponService_ServiceDesc is the grpc.ServiceDesc for CouponService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CouponService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "couponProto.CouponService",
	HandlerType: (*CouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDistributeTask",
			Handler:    _CouponService_CreateDistributeTask_Handler,
		},
		{
			MethodName: "ExecuteDistributeTask",
			Handler:    _CouponService_ExecuteDistributeTask_Handler,
		},
		{
			MethodName: "UserGetCoupon",
			Handler:    _CouponService_UserGetCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coupon_service.proto",
}
